[2020-11-19 10:39:47,922: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 10:39:49,930: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 10:39:53,940: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 10:39:59,951: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 10:40:07,966: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 10:40:17,981: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 10:40:29,998: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 10:40:44,019: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 10:41:00,041: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 10:41:09,243: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 10:41:11,251: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 10:41:15,261: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 10:41:18,064: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 10:41:21,273: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 10:41:29,287: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 10:41:38,091: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 10:41:39,303: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 10:41:51,322: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 10:42:00,120: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 10:42:05,342: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 10:42:21,364: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 10:42:24,149: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 10:42:39,388: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 10:42:50,182: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 10:42:59,415: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 10:43:18,218: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 10:43:21,444: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 10:43:45,475: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 10:43:48,255: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 11:44:05,338: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 11:44:07,342: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 11:44:11,348: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 11:44:17,357: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 11:44:25,367: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 11:44:35,380: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 11:44:47,395: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 11:45:01,410: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 11:45:17,429: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 12:14:27,679: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 12:14:29,683: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 12:14:33,690: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 12:14:39,698: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 12:14:47,708: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 12:14:57,721: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 12:15:09,736: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 12:15:23,753: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 12:15:39,772: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 12:15:57,793: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 12:16:17,815: ERROR/MainProcess] consumer: Cannot connect to redis://guest:**@broker:6379//: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 12:16:29,885: INFO/MainProcess] Connected to redis://broker:6379//
[2020-11-19 12:16:29,899: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2020-11-19 12:16:29,899: INFO/MainProcess] celery@76d1f22d85a4 ready.
[2020-11-19 12:16:29,901: INFO/MainProcess] Received task: core.tasks.every_10_sec[1438c650-f32b-42e9-9595-635c8383fd15]  
[2020-11-19 12:16:29,901: INFO/MainProcess] core.tasks.every_10_sec[1438c650-f32b-42e9-9595-635c8383fd15]: Run every 10sec methods
[2020-11-19 12:16:29,902: INFO/MainProcess] core.tasks.every_10_sec[1438c650-f32b-42e9-9595-635c8383fd15]: result: 166
[2020-11-19 12:16:29,902: INFO/MainProcess] Task core.tasks.every_10_sec[1438c650-f32b-42e9-9595-635c8383fd15] succeeded in 0.0007923999946797267s: 166
[2020-11-19 12:16:29,905: INFO/MainProcess] Received task: core.tasks.every_30_sec[a954747c-9faa-4d1b-9eb7-089492ae719c]  
[2020-11-19 12:16:29,905: INFO/MainProcess] core.tasks.every_30_sec[a954747c-9faa-4d1b-9eb7-089492ae719c]: Run every 30sec methods
[2020-11-19 12:16:29,905: INFO/MainProcess] core.tasks.every_30_sec[a954747c-9faa-4d1b-9eb7-089492ae719c]: result: 370
[2020-11-19 12:16:29,906: INFO/MainProcess] Task core.tasks.every_30_sec[a954747c-9faa-4d1b-9eb7-089492ae719c] succeeded in 0.0008112999930744991s: 370
[2020-11-19 12:16:29,908: INFO/MainProcess] Received task: core.tasks.every_60_sec[cce8e4b1-88bc-4602-900c-4d5d9d1a0a8e]  
[2020-11-19 12:16:29,909: INFO/MainProcess] core.tasks.every_60_sec[cce8e4b1-88bc-4602-900c-4d5d9d1a0a8e]: Run every 60sec methods
[2020-11-19 12:16:29,910: INFO/MainProcess] core.tasks.every_60_sec[cce8e4b1-88bc-4602-900c-4d5d9d1a0a8e]: result: 784
[2020-11-19 12:16:29,910: INFO/MainProcess] Task core.tasks.every_60_sec[cce8e4b1-88bc-4602-900c-4d5d9d1a0a8e] succeeded in 0.0009978000016417354s: 784
[2020-11-19 12:16:29,912: INFO/MainProcess] Received task: core.tasks.every_10_sec[b90afb1b-2c06-413b-963b-5bc4d52777aa]  
[2020-11-19 12:16:29,913: INFO/MainProcess] core.tasks.every_10_sec[b90afb1b-2c06-413b-963b-5bc4d52777aa]: Run every 10sec methods
[2020-11-19 12:16:29,913: INFO/MainProcess] core.tasks.every_10_sec[b90afb1b-2c06-413b-963b-5bc4d52777aa]: result: 18
[2020-11-19 12:16:29,913: INFO/MainProcess] Task core.tasks.every_10_sec[b90afb1b-2c06-413b-963b-5bc4d52777aa] succeeded in 0.0007562999962829053s: 18
[2020-11-19 12:16:29,915: INFO/MainProcess] Received task: core.tasks.every_10_sec[0d0d18ba-9bbc-433e-897a-9a293374d853]  
[2020-11-19 12:16:29,915: INFO/MainProcess] core.tasks.every_10_sec[0d0d18ba-9bbc-433e-897a-9a293374d853]: Run every 10sec methods
[2020-11-19 12:16:29,916: INFO/MainProcess] core.tasks.every_10_sec[0d0d18ba-9bbc-433e-897a-9a293374d853]: result: 101
[2020-11-19 12:16:29,916: INFO/MainProcess] Task core.tasks.every_10_sec[0d0d18ba-9bbc-433e-897a-9a293374d853] succeeded in 0.0007253000076161698s: 101
[2020-11-19 12:16:29,918: INFO/MainProcess] Received task: core.tasks.every_10_sec[c09232e3-0e53-4d40-9fa7-202bf92ae52c]  
[2020-11-19 12:16:29,918: INFO/MainProcess] core.tasks.every_10_sec[c09232e3-0e53-4d40-9fa7-202bf92ae52c]: Run every 10sec methods
[2020-11-19 12:16:29,919: INFO/MainProcess] core.tasks.every_10_sec[c09232e3-0e53-4d40-9fa7-202bf92ae52c]: result: 114
[2020-11-19 12:16:29,919: INFO/MainProcess] Task core.tasks.every_10_sec[c09232e3-0e53-4d40-9fa7-202bf92ae52c] succeeded in 0.0007228000031318516s: 114
[2020-11-19 12:16:29,921: INFO/MainProcess] Received task: core.tasks.every_30_sec[a1d32ef7-7b34-45ad-a3ab-dbf4c68d7226]  
[2020-11-19 12:16:29,921: INFO/MainProcess] core.tasks.every_30_sec[a1d32ef7-7b34-45ad-a3ab-dbf4c68d7226]: Run every 30sec methods
[2020-11-19 12:16:29,922: INFO/MainProcess] core.tasks.every_30_sec[a1d32ef7-7b34-45ad-a3ab-dbf4c68d7226]: result: 425
[2020-11-19 12:16:29,922: INFO/MainProcess] Task core.tasks.every_30_sec[a1d32ef7-7b34-45ad-a3ab-dbf4c68d7226] succeeded in 0.0007273000082932413s: 425
[2020-11-19 12:16:29,924: INFO/MainProcess] Received task: core.tasks.every_10_sec[2fdbfbc8-260f-45a5-a13f-e9fa7a49082c]  
[2020-11-19 12:16:29,924: INFO/MainProcess] core.tasks.every_10_sec[2fdbfbc8-260f-45a5-a13f-e9fa7a49082c]: Run every 10sec methods
[2020-11-19 12:16:29,925: INFO/MainProcess] core.tasks.every_10_sec[2fdbfbc8-260f-45a5-a13f-e9fa7a49082c]: result: 188
[2020-11-19 12:16:29,925: INFO/MainProcess] Task core.tasks.every_10_sec[2fdbfbc8-260f-45a5-a13f-e9fa7a49082c] succeeded in 0.0007996000058483332s: 188
[2020-11-19 12:16:29,927: INFO/MainProcess] Received task: core.tasks.every_10_sec[64cab5cc-81e0-462a-9268-2999aecf8749]  
[2020-11-19 12:16:29,928: INFO/MainProcess] core.tasks.every_10_sec[64cab5cc-81e0-462a-9268-2999aecf8749]: Run every 10sec methods
[2020-11-19 12:16:29,928: INFO/MainProcess] core.tasks.every_10_sec[64cab5cc-81e0-462a-9268-2999aecf8749]: result: 99
[2020-11-19 12:16:29,928: INFO/MainProcess] Task core.tasks.every_10_sec[64cab5cc-81e0-462a-9268-2999aecf8749] succeeded in 0.0007907000108389184s: 99
[2020-11-19 12:16:29,930: INFO/MainProcess] Received task: core.tasks.every_10_sec[e5acdbbc-8966-4d21-afaa-9c60f8386ffa]  
[2020-11-19 12:16:29,931: INFO/MainProcess] core.tasks.every_10_sec[e5acdbbc-8966-4d21-afaa-9c60f8386ffa]: Run every 10sec methods
[2020-11-19 12:16:29,931: INFO/MainProcess] core.tasks.every_10_sec[e5acdbbc-8966-4d21-afaa-9c60f8386ffa]: result: 102
[2020-11-19 12:16:29,931: INFO/MainProcess] Task core.tasks.every_10_sec[e5acdbbc-8966-4d21-afaa-9c60f8386ffa] succeeded in 0.0008411000017076731s: 102
[2020-11-19 12:16:29,933: INFO/MainProcess] Received task: core.tasks.every_30_sec[373d4a27-f8d3-42ee-acb4-af08c0e05b86]  
[2020-11-19 12:16:29,934: INFO/MainProcess] core.tasks.every_30_sec[373d4a27-f8d3-42ee-acb4-af08c0e05b86]: Run every 30sec methods
[2020-11-19 12:16:29,934: INFO/MainProcess] core.tasks.every_30_sec[373d4a27-f8d3-42ee-acb4-af08c0e05b86]: result: 328
[2020-11-19 12:16:29,934: INFO/MainProcess] Task core.tasks.every_30_sec[373d4a27-f8d3-42ee-acb4-af08c0e05b86] succeeded in 0.0007831000111764297s: 328
[2020-11-19 12:16:29,936: INFO/MainProcess] Received task: core.tasks.every_60_sec[c659a1c0-e7b6-4b35-8443-478e5f56b41a]  
[2020-11-19 12:16:29,937: INFO/MainProcess] core.tasks.every_60_sec[c659a1c0-e7b6-4b35-8443-478e5f56b41a]: Run every 60sec methods
[2020-11-19 12:16:29,937: INFO/MainProcess] core.tasks.every_60_sec[c659a1c0-e7b6-4b35-8443-478e5f56b41a]: result: 754
[2020-11-19 12:16:29,937: INFO/MainProcess] Task core.tasks.every_60_sec[c659a1c0-e7b6-4b35-8443-478e5f56b41a] succeeded in 0.0007570000016130507s: 754
[2020-11-19 12:16:29,939: INFO/MainProcess] Received task: core.tasks.every_10_sec[f9cc7419-88ac-4805-b216-26ee023dfaa0]  
[2020-11-19 12:16:29,940: INFO/MainProcess] core.tasks.every_10_sec[f9cc7419-88ac-4805-b216-26ee023dfaa0]: Run every 10sec methods
[2020-11-19 12:16:29,940: INFO/MainProcess] core.tasks.every_10_sec[f9cc7419-88ac-4805-b216-26ee023dfaa0]: result: 133
[2020-11-19 12:16:29,940: INFO/MainProcess] Task core.tasks.every_10_sec[f9cc7419-88ac-4805-b216-26ee023dfaa0] succeeded in 0.0008632999961264431s: 133
[2020-11-19 12:16:29,942: INFO/MainProcess] Received task: core.tasks.every_10_sec[601e8ea5-45f8-41a4-892d-8fa596525cbb]  
[2020-11-19 12:16:29,943: INFO/MainProcess] core.tasks.every_10_sec[601e8ea5-45f8-41a4-892d-8fa596525cbb]: Run every 10sec methods
[2020-11-19 12:16:29,943: INFO/MainProcess] core.tasks.every_10_sec[601e8ea5-45f8-41a4-892d-8fa596525cbb]: result: 149
[2020-11-19 12:16:29,943: INFO/MainProcess] Task core.tasks.every_10_sec[601e8ea5-45f8-41a4-892d-8fa596525cbb] succeeded in 0.0007771000091452152s: 149
[2020-11-19 12:16:29,945: INFO/MainProcess] Received task: core.tasks.every_10_sec[dd1b4328-ccc6-4186-a4d7-c833615220b9]  
[2020-11-19 12:16:29,946: INFO/MainProcess] core.tasks.every_10_sec[dd1b4328-ccc6-4186-a4d7-c833615220b9]: Run every 10sec methods
[2020-11-19 12:16:29,946: INFO/MainProcess] core.tasks.every_10_sec[dd1b4328-ccc6-4186-a4d7-c833615220b9]: result: 128
[2020-11-19 12:16:29,946: INFO/MainProcess] Task core.tasks.every_10_sec[dd1b4328-ccc6-4186-a4d7-c833615220b9] succeeded in 0.0007485999958589673s: 128
[2020-11-19 12:16:29,948: INFO/MainProcess] Received task: core.tasks.every_30_sec[b43f473c-f3b8-4f52-8c6c-e3780ecbfdbb]  
[2020-11-19 12:16:29,948: INFO/MainProcess] core.tasks.every_30_sec[b43f473c-f3b8-4f52-8c6c-e3780ecbfdbb]: Run every 30sec methods
[2020-11-19 12:16:29,949: INFO/MainProcess] core.tasks.every_30_sec[b43f473c-f3b8-4f52-8c6c-e3780ecbfdbb]: result: 383
[2020-11-19 12:16:29,949: INFO/MainProcess] Task core.tasks.every_30_sec[b43f473c-f3b8-4f52-8c6c-e3780ecbfdbb] succeeded in 0.0007994000043254346s: 383
[2020-11-19 12:16:29,951: INFO/MainProcess] Received task: core.tasks.every_10_sec[8dcf7864-fdf7-4489-9bfc-25919e371a76]  
[2020-11-19 12:16:29,951: INFO/MainProcess] core.tasks.every_10_sec[8dcf7864-fdf7-4489-9bfc-25919e371a76]: Run every 10sec methods
[2020-11-19 12:16:29,952: INFO/MainProcess] core.tasks.every_10_sec[8dcf7864-fdf7-4489-9bfc-25919e371a76]: result: 131
[2020-11-19 12:16:29,952: INFO/MainProcess] Task core.tasks.every_10_sec[8dcf7864-fdf7-4489-9bfc-25919e371a76] succeeded in 0.0007518000056734309s: 131
[2020-11-19 12:16:29,954: INFO/MainProcess] Received task: core.tasks.every_10_sec[d12ea059-86b4-4c70-81e5-e1e0fb30e6d5]  
[2020-11-19 12:16:29,954: INFO/MainProcess] core.tasks.every_10_sec[d12ea059-86b4-4c70-81e5-e1e0fb30e6d5]: Run every 10sec methods
[2020-11-19 12:16:29,955: INFO/MainProcess] core.tasks.every_10_sec[d12ea059-86b4-4c70-81e5-e1e0fb30e6d5]: result: 95
[2020-11-19 12:16:29,955: INFO/MainProcess] Task core.tasks.every_10_sec[d12ea059-86b4-4c70-81e5-e1e0fb30e6d5] succeeded in 0.0007362000033026561s: 95
[2020-11-19 12:16:29,957: INFO/MainProcess] Received task: core.tasks.every_10_sec[94c8a3d3-a57b-4922-a22f-ee11d34bb473]  
[2020-11-19 12:16:29,958: INFO/MainProcess] core.tasks.every_10_sec[94c8a3d3-a57b-4922-a22f-ee11d34bb473]: Run every 10sec methods
[2020-11-19 12:16:29,958: INFO/MainProcess] core.tasks.every_10_sec[94c8a3d3-a57b-4922-a22f-ee11d34bb473]: result: 59
[2020-11-19 12:16:29,959: INFO/MainProcess] Task core.tasks.every_10_sec[94c8a3d3-a57b-4922-a22f-ee11d34bb473] succeeded in 0.0009204999951180071s: 59
[2020-11-19 12:16:29,960: INFO/MainProcess] Received task: core.tasks.every_30_sec[ddd8ecb0-6dd7-42f4-82f4-d9c794a00409]  
[2020-11-19 12:16:29,961: INFO/MainProcess] core.tasks.every_30_sec[ddd8ecb0-6dd7-42f4-82f4-d9c794a00409]: Run every 30sec methods
[2020-11-19 12:16:29,961: INFO/MainProcess] core.tasks.every_30_sec[ddd8ecb0-6dd7-42f4-82f4-d9c794a00409]: result: 377
[2020-11-19 12:16:29,961: INFO/MainProcess] Task core.tasks.every_30_sec[ddd8ecb0-6dd7-42f4-82f4-d9c794a00409] succeeded in 0.0007824999920558184s: 377
[2020-11-19 12:16:29,963: INFO/MainProcess] Received task: core.tasks.every_60_sec[e362e7bf-3d79-4691-81ef-91e4646be7d8]  
[2020-11-19 12:16:29,964: INFO/MainProcess] core.tasks.every_60_sec[e362e7bf-3d79-4691-81ef-91e4646be7d8]: Run every 60sec methods
[2020-11-19 12:16:29,964: INFO/MainProcess] core.tasks.every_60_sec[e362e7bf-3d79-4691-81ef-91e4646be7d8]: result: 808
[2020-11-19 12:16:29,964: INFO/MainProcess] Task core.tasks.every_60_sec[e362e7bf-3d79-4691-81ef-91e4646be7d8] succeeded in 0.0007784000044921413s: 808
[2020-11-19 12:16:29,966: INFO/MainProcess] Received task: core.tasks.every_10_sec[de683874-a01a-467a-b0ff-8a9f43710191]  
[2020-11-19 12:16:29,967: INFO/MainProcess] core.tasks.every_10_sec[de683874-a01a-467a-b0ff-8a9f43710191]: Run every 10sec methods
[2020-11-19 12:16:29,967: INFO/MainProcess] core.tasks.every_10_sec[de683874-a01a-467a-b0ff-8a9f43710191]: result: 96
[2020-11-19 12:16:29,967: INFO/MainProcess] Task core.tasks.every_10_sec[de683874-a01a-467a-b0ff-8a9f43710191] succeeded in 0.0008093999931588769s: 96
[2020-11-19 12:16:29,969: INFO/MainProcess] Received task: core.tasks.every_10_sec[23dc6ac0-8737-4cca-abe3-2b8eaf06d7bb]  
[2020-11-19 12:16:29,969: INFO/MainProcess] core.tasks.every_10_sec[23dc6ac0-8737-4cca-abe3-2b8eaf06d7bb]: Run every 10sec methods
[2020-11-19 12:16:29,970: INFO/MainProcess] core.tasks.every_10_sec[23dc6ac0-8737-4cca-abe3-2b8eaf06d7bb]: result: 153
[2020-11-19 12:16:29,970: INFO/MainProcess] Task core.tasks.every_10_sec[23dc6ac0-8737-4cca-abe3-2b8eaf06d7bb] succeeded in 0.0007712999940849841s: 153
[2020-11-19 12:16:29,972: INFO/MainProcess] Received task: core.tasks.every_10_sec[a09b7b8b-19ca-4688-8899-11b4b8685ee7]  
[2020-11-19 12:16:29,972: INFO/MainProcess] core.tasks.every_10_sec[a09b7b8b-19ca-4688-8899-11b4b8685ee7]: Run every 10sec methods
[2020-11-19 12:16:29,973: INFO/MainProcess] core.tasks.every_10_sec[a09b7b8b-19ca-4688-8899-11b4b8685ee7]: result: 158
[2020-11-19 12:16:29,973: INFO/MainProcess] Task core.tasks.every_10_sec[a09b7b8b-19ca-4688-8899-11b4b8685ee7] succeeded in 0.0009758999949553981s: 158
[2020-11-19 12:16:29,975: INFO/MainProcess] Received task: core.tasks.every_30_sec[ea168e75-5754-425a-9b95-165cca8037c4]  
[2020-11-19 12:16:29,976: INFO/MainProcess] core.tasks.every_30_sec[ea168e75-5754-425a-9b95-165cca8037c4]: Run every 30sec methods
[2020-11-19 12:16:29,976: INFO/MainProcess] core.tasks.every_30_sec[ea168e75-5754-425a-9b95-165cca8037c4]: result: 330
[2020-11-19 12:16:29,976: INFO/MainProcess] Task core.tasks.every_30_sec[ea168e75-5754-425a-9b95-165cca8037c4] succeeded in 0.0007689000049140304s: 330
[2020-11-19 12:16:29,978: INFO/MainProcess] Received task: core.tasks.every_10_sec[131444a5-f1f3-457a-b8d3-85b823e6db46]  
[2020-11-19 12:16:29,979: INFO/MainProcess] core.tasks.every_10_sec[131444a5-f1f3-457a-b8d3-85b823e6db46]: Run every 10sec methods
[2020-11-19 12:16:29,979: INFO/MainProcess] core.tasks.every_10_sec[131444a5-f1f3-457a-b8d3-85b823e6db46]: result: 115
[2020-11-19 12:16:29,979: INFO/MainProcess] Task core.tasks.every_10_sec[131444a5-f1f3-457a-b8d3-85b823e6db46] succeeded in 0.0007465999951818958s: 115
[2020-11-19 12:16:29,981: INFO/MainProcess] Received task: core.tasks.every_10_sec[6595e894-296b-4df7-8cae-725921311d9a]  
[2020-11-19 12:16:29,981: INFO/MainProcess] core.tasks.every_10_sec[6595e894-296b-4df7-8cae-725921311d9a]: Run every 10sec methods
[2020-11-19 12:16:29,982: INFO/MainProcess] core.tasks.every_10_sec[6595e894-296b-4df7-8cae-725921311d9a]: result: 164
[2020-11-19 12:16:29,982: INFO/MainProcess] Task core.tasks.every_10_sec[6595e894-296b-4df7-8cae-725921311d9a] succeeded in 0.0007479999912902713s: 164
[2020-11-19 12:16:29,984: INFO/MainProcess] Received task: core.tasks.every_10_sec[1a59f491-047e-4aa5-8d25-96a5c7428d5c]  
[2020-11-19 12:16:29,984: INFO/MainProcess] core.tasks.every_10_sec[1a59f491-047e-4aa5-8d25-96a5c7428d5c]: Run every 10sec methods
[2020-11-19 12:16:29,985: INFO/MainProcess] core.tasks.every_10_sec[1a59f491-047e-4aa5-8d25-96a5c7428d5c]: result: 70
[2020-11-19 12:16:29,985: INFO/MainProcess] Task core.tasks.every_10_sec[1a59f491-047e-4aa5-8d25-96a5c7428d5c] succeeded in 0.0007196000078693032s: 70
[2020-11-19 12:16:29,987: INFO/MainProcess] Received task: core.tasks.every_30_sec[9c3228bf-3bc2-4293-9b23-0e7289a8450a]  
[2020-11-19 12:16:29,987: INFO/MainProcess] core.tasks.every_30_sec[9c3228bf-3bc2-4293-9b23-0e7289a8450a]: Run every 30sec methods
[2020-11-19 12:16:29,988: INFO/MainProcess] core.tasks.every_30_sec[9c3228bf-3bc2-4293-9b23-0e7289a8450a]: result: 356
[2020-11-19 12:16:29,988: INFO/MainProcess] Task core.tasks.every_30_sec[9c3228bf-3bc2-4293-9b23-0e7289a8450a] succeeded in 0.0007178000087151304s: 356
[2020-11-19 12:16:29,990: INFO/MainProcess] Received task: core.tasks.every_60_sec[8b07209e-369c-40f5-b2b4-6eb26291b332]  
[2020-11-19 12:16:29,991: INFO/MainProcess] core.tasks.every_60_sec[8b07209e-369c-40f5-b2b4-6eb26291b332]: Run every 60sec methods
[2020-11-19 12:16:29,991: INFO/MainProcess] core.tasks.every_60_sec[8b07209e-369c-40f5-b2b4-6eb26291b332]: result: 804
[2020-11-19 12:16:29,992: INFO/MainProcess] Task core.tasks.every_60_sec[8b07209e-369c-40f5-b2b4-6eb26291b332] succeeded in 0.0010399000020697713s: 804
[2020-11-19 12:16:29,994: INFO/MainProcess] Received task: core.tasks.every_10_sec[4199d580-2006-4743-ac43-2a9243738e50]  
[2020-11-19 12:16:29,994: INFO/MainProcess] core.tasks.every_10_sec[4199d580-2006-4743-ac43-2a9243738e50]: Run every 10sec methods
[2020-11-19 12:16:29,994: INFO/MainProcess] core.tasks.every_10_sec[4199d580-2006-4743-ac43-2a9243738e50]: result: 34
[2020-11-19 12:16:29,995: INFO/MainProcess] Task core.tasks.every_10_sec[4199d580-2006-4743-ac43-2a9243738e50] succeeded in 0.0008304999937536195s: 34
[2020-11-19 12:16:29,997: INFO/MainProcess] Received task: core.tasks.every_10_sec[3d46851c-d292-4844-8b79-24bbb61f2f9a]  
[2020-11-19 12:16:29,997: INFO/MainProcess] core.tasks.every_10_sec[3d46851c-d292-4844-8b79-24bbb61f2f9a]: Run every 10sec methods
[2020-11-19 12:16:29,997: INFO/MainProcess] core.tasks.every_10_sec[3d46851c-d292-4844-8b79-24bbb61f2f9a]: result: 134
[2020-11-19 12:16:29,998: INFO/MainProcess] Task core.tasks.every_10_sec[3d46851c-d292-4844-8b79-24bbb61f2f9a] succeeded in 0.0007601000106660649s: 134
[2020-11-19 12:16:29,999: INFO/MainProcess] Received task: core.tasks.every_10_sec[ab818811-8940-4b45-af5f-61b22c154f89]  
[2020-11-19 12:16:30,000: INFO/MainProcess] core.tasks.every_10_sec[ab818811-8940-4b45-af5f-61b22c154f89]: Run every 10sec methods
[2020-11-19 12:16:30,000: INFO/MainProcess] core.tasks.every_10_sec[ab818811-8940-4b45-af5f-61b22c154f89]: result: 174
[2020-11-19 12:16:30,001: INFO/MainProcess] Task core.tasks.every_10_sec[ab818811-8940-4b45-af5f-61b22c154f89] succeeded in 0.0008105000015348196s: 174
[2020-11-19 12:16:30,002: INFO/MainProcess] Received task: core.tasks.every_30_sec[a6fc6dcf-f349-40e9-a130-977448c79067]  
[2020-11-19 12:16:30,003: INFO/MainProcess] core.tasks.every_30_sec[a6fc6dcf-f349-40e9-a130-977448c79067]: Run every 30sec methods
[2020-11-19 12:16:30,003: INFO/MainProcess] core.tasks.every_30_sec[a6fc6dcf-f349-40e9-a130-977448c79067]: result: 447
[2020-11-19 12:16:30,004: INFO/MainProcess] Task core.tasks.every_30_sec[a6fc6dcf-f349-40e9-a130-977448c79067] succeeded in 0.0007715999963693321s: 447
[2020-11-19 12:16:30,005: INFO/MainProcess] Received task: core.tasks.every_10_sec[081b8e9e-401d-4817-93a9-7ae10b720437]  
[2020-11-19 12:16:30,006: INFO/MainProcess] core.tasks.every_10_sec[081b8e9e-401d-4817-93a9-7ae10b720437]: Run every 10sec methods
[2020-11-19 12:16:30,007: INFO/MainProcess] core.tasks.every_10_sec[081b8e9e-401d-4817-93a9-7ae10b720437]: result: 79
[2020-11-19 12:16:30,007: INFO/MainProcess] Task core.tasks.every_10_sec[081b8e9e-401d-4817-93a9-7ae10b720437] succeeded in 0.0009614000009605661s: 79
[2020-11-19 12:16:30,009: INFO/MainProcess] Received task: core.tasks.every_10_sec[fa06047d-2ddc-4e4f-ad7b-9f45d9d00edf]  
[2020-11-19 12:16:30,009: INFO/MainProcess] core.tasks.every_10_sec[fa06047d-2ddc-4e4f-ad7b-9f45d9d00edf]: Run every 10sec methods
[2020-11-19 12:16:30,010: INFO/MainProcess] core.tasks.every_10_sec[fa06047d-2ddc-4e4f-ad7b-9f45d9d00edf]: result: 123
[2020-11-19 12:16:30,010: INFO/MainProcess] Task core.tasks.every_10_sec[fa06047d-2ddc-4e4f-ad7b-9f45d9d00edf] succeeded in 0.0007506999972974882s: 123
[2020-11-19 12:16:30,012: INFO/MainProcess] Received task: core.tasks.every_10_sec[32a723c6-bdac-4e43-9c9b-d8cda370acb4]  
[2020-11-19 12:16:30,012: INFO/MainProcess] core.tasks.every_10_sec[32a723c6-bdac-4e43-9c9b-d8cda370acb4]: Run every 10sec methods
[2020-11-19 12:16:30,012: INFO/MainProcess] core.tasks.every_10_sec[32a723c6-bdac-4e43-9c9b-d8cda370acb4]: result: 74
[2020-11-19 12:16:30,013: INFO/MainProcess] Task core.tasks.every_10_sec[32a723c6-bdac-4e43-9c9b-d8cda370acb4] succeeded in 0.0007643999997526407s: 74
[2020-11-19 12:16:30,015: INFO/MainProcess] Received task: core.tasks.every_30_sec[698838db-faed-4f1a-8191-ec253f3d0be7]  
[2020-11-19 12:16:30,015: INFO/MainProcess] core.tasks.every_30_sec[698838db-faed-4f1a-8191-ec253f3d0be7]: Run every 30sec methods
[2020-11-19 12:16:30,015: INFO/MainProcess] core.tasks.every_30_sec[698838db-faed-4f1a-8191-ec253f3d0be7]: result: 432
[2020-11-19 12:16:30,016: INFO/MainProcess] Task core.tasks.every_30_sec[698838db-faed-4f1a-8191-ec253f3d0be7] succeeded in 0.0007661000126972795s: 432
[2020-11-19 12:16:30,017: INFO/MainProcess] Received task: core.tasks.every_60_sec[28d8f7d1-eda5-4dc3-b434-d11aad1232b2]  
[2020-11-19 12:16:30,018: INFO/MainProcess] core.tasks.every_60_sec[28d8f7d1-eda5-4dc3-b434-d11aad1232b2]: Run every 60sec methods
[2020-11-19 12:16:30,018: INFO/MainProcess] core.tasks.every_60_sec[28d8f7d1-eda5-4dc3-b434-d11aad1232b2]: result: 798
[2020-11-19 12:16:30,019: INFO/MainProcess] Task core.tasks.every_60_sec[28d8f7d1-eda5-4dc3-b434-d11aad1232b2] succeeded in 0.0007651000050827861s: 798
[2020-11-19 12:16:30,020: INFO/MainProcess] Received task: core.tasks.every_10_sec[d8671ced-d276-42eb-ae11-4eb5e1f5eb7f]  
[2020-11-19 12:16:30,021: INFO/MainProcess] core.tasks.every_10_sec[d8671ced-d276-42eb-ae11-4eb5e1f5eb7f]: Run every 10sec methods
[2020-11-19 12:16:30,021: INFO/MainProcess] core.tasks.every_10_sec[d8671ced-d276-42eb-ae11-4eb5e1f5eb7f]: result: 105
[2020-11-19 12:16:30,022: INFO/MainProcess] Task core.tasks.every_10_sec[d8671ced-d276-42eb-ae11-4eb5e1f5eb7f] succeeded in 0.0008335000020451844s: 105
[2020-11-19 12:16:30,024: INFO/MainProcess] Received task: core.tasks.every_10_sec[96e7dbc7-6ec0-4b4f-a78c-dea9bff08c74]  
[2020-11-19 12:16:30,024: INFO/MainProcess] core.tasks.every_10_sec[96e7dbc7-6ec0-4b4f-a78c-dea9bff08c74]: Run every 10sec methods
[2020-11-19 12:16:30,025: INFO/MainProcess] core.tasks.every_10_sec[96e7dbc7-6ec0-4b4f-a78c-dea9bff08c74]: result: 81
[2020-11-19 12:16:30,025: INFO/MainProcess] Task core.tasks.every_10_sec[96e7dbc7-6ec0-4b4f-a78c-dea9bff08c74] succeeded in 0.0007863999926485121s: 81
[2020-11-19 12:16:30,027: INFO/MainProcess] Received task: core.tasks.every_10_sec[34c18ac7-b6fc-4224-81a3-f6b94a8551fb]  
[2020-11-19 12:16:30,027: INFO/MainProcess] core.tasks.every_10_sec[34c18ac7-b6fc-4224-81a3-f6b94a8551fb]: Run every 10sec methods
[2020-11-19 12:16:30,028: INFO/MainProcess] core.tasks.every_10_sec[34c18ac7-b6fc-4224-81a3-f6b94a8551fb]: result: 133
[2020-11-19 12:16:30,028: INFO/MainProcess] Task core.tasks.every_10_sec[34c18ac7-b6fc-4224-81a3-f6b94a8551fb] succeeded in 0.0008633999968878925s: 133
[2020-11-19 12:16:30,030: INFO/MainProcess] Received task: core.tasks.every_30_sec[7073700c-bd61-4f4d-89e6-a8edb748928d]  
[2020-11-19 12:16:30,030: INFO/MainProcess] core.tasks.every_30_sec[7073700c-bd61-4f4d-89e6-a8edb748928d]: Run every 30sec methods
[2020-11-19 12:16:30,031: INFO/MainProcess] core.tasks.every_30_sec[7073700c-bd61-4f4d-89e6-a8edb748928d]: result: 393
[2020-11-19 12:16:30,031: INFO/MainProcess] Task core.tasks.every_30_sec[7073700c-bd61-4f4d-89e6-a8edb748928d] succeeded in 0.0007982999959494919s: 393
[2020-11-19 12:16:30,033: INFO/MainProcess] Received task: core.tasks.every_10_sec[ec40f38c-f519-4b83-9954-0b635fb33ac4]  
[2020-11-19 12:16:30,033: INFO/MainProcess] core.tasks.every_10_sec[ec40f38c-f519-4b83-9954-0b635fb33ac4]: Run every 10sec methods
[2020-11-19 12:16:30,033: INFO/MainProcess] core.tasks.every_10_sec[ec40f38c-f519-4b83-9954-0b635fb33ac4]: result: 27
[2020-11-19 12:16:30,034: INFO/MainProcess] Task core.tasks.every_10_sec[ec40f38c-f519-4b83-9954-0b635fb33ac4] succeeded in 0.0007227999885799363s: 27
[2020-11-19 12:16:30,035: INFO/MainProcess] Received task: core.tasks.every_10_sec[c6ae7c26-6886-4328-aca7-9e2ad604d06e]  
[2020-11-19 12:16:30,036: INFO/MainProcess] core.tasks.every_10_sec[c6ae7c26-6886-4328-aca7-9e2ad604d06e]: Run every 10sec methods
[2020-11-19 12:16:30,036: INFO/MainProcess] core.tasks.every_10_sec[c6ae7c26-6886-4328-aca7-9e2ad604d06e]: result: 127
[2020-11-19 12:16:30,037: INFO/MainProcess] Task core.tasks.every_10_sec[c6ae7c26-6886-4328-aca7-9e2ad604d06e] succeeded in 0.0009511000098427758s: 127
[2020-11-19 12:16:30,039: INFO/MainProcess] Received task: core.tasks.every_10_sec[244092e6-0d9c-4695-8f56-c365db496e81]  
[2020-11-19 12:16:30,039: INFO/MainProcess] core.tasks.every_10_sec[244092e6-0d9c-4695-8f56-c365db496e81]: Run every 10sec methods
[2020-11-19 12:16:30,040: INFO/MainProcess] core.tasks.every_10_sec[244092e6-0d9c-4695-8f56-c365db496e81]: result: 115
[2020-11-19 12:16:30,040: INFO/MainProcess] Task core.tasks.every_10_sec[244092e6-0d9c-4695-8f56-c365db496e81] succeeded in 0.0009164000075543299s: 115
[2020-11-19 12:16:30,042: INFO/MainProcess] Received task: core.tasks.every_30_sec[6dceefdf-5b13-4fff-b4c1-75e3cec4308a]  
[2020-11-19 12:16:30,043: INFO/MainProcess] core.tasks.every_30_sec[6dceefdf-5b13-4fff-b4c1-75e3cec4308a]: Run every 30sec methods
[2020-11-19 12:16:30,043: INFO/MainProcess] core.tasks.every_30_sec[6dceefdf-5b13-4fff-b4c1-75e3cec4308a]: result: 392
[2020-11-19 12:16:30,043: INFO/MainProcess] Task core.tasks.every_30_sec[6dceefdf-5b13-4fff-b4c1-75e3cec4308a] succeeded in 0.0007871999987401068s: 392
[2020-11-19 12:16:30,045: INFO/MainProcess] Received task: core.tasks.every_60_sec[aec22fbf-7794-4961-8e0c-d2c75158af5e]  
[2020-11-19 12:16:30,046: INFO/MainProcess] core.tasks.every_60_sec[aec22fbf-7794-4961-8e0c-d2c75158af5e]: Run every 60sec methods
[2020-11-19 12:16:30,046: INFO/MainProcess] core.tasks.every_60_sec[aec22fbf-7794-4961-8e0c-d2c75158af5e]: result: 815
[2020-11-19 12:16:30,046: INFO/MainProcess] Task core.tasks.every_60_sec[aec22fbf-7794-4961-8e0c-d2c75158af5e] succeeded in 0.0007726000039838254s: 815
[2020-11-19 12:16:30,048: INFO/MainProcess] Received task: core.tasks.every_10_sec[3e28ec8c-2561-49e5-8293-f41069ad55b7]  
[2020-11-19 12:16:30,048: INFO/MainProcess] core.tasks.every_10_sec[3e28ec8c-2561-49e5-8293-f41069ad55b7]: Run every 10sec methods
[2020-11-19 12:16:30,049: INFO/MainProcess] core.tasks.every_10_sec[3e28ec8c-2561-49e5-8293-f41069ad55b7]: result: 99
[2020-11-19 12:16:30,049: INFO/MainProcess] Task core.tasks.every_10_sec[3e28ec8c-2561-49e5-8293-f41069ad55b7] succeeded in 0.0007583999977214262s: 99
[2020-11-19 12:16:30,051: INFO/MainProcess] Received task: core.tasks.every_10_sec[58250f23-5557-4f76-9e8a-032590e6d1d6]  
[2020-11-19 12:16:30,051: INFO/MainProcess] core.tasks.every_10_sec[58250f23-5557-4f76-9e8a-032590e6d1d6]: Run every 10sec methods
[2020-11-19 12:16:30,052: INFO/MainProcess] core.tasks.every_10_sec[58250f23-5557-4f76-9e8a-032590e6d1d6]: result: 62
[2020-11-19 12:16:30,052: INFO/MainProcess] Task core.tasks.every_10_sec[58250f23-5557-4f76-9e8a-032590e6d1d6] succeeded in 0.0007538000063505024s: 62
[2020-11-19 12:16:30,054: INFO/MainProcess] Received task: core.tasks.every_10_sec[ec3b26f3-b469-4caf-9437-d8aba0ba8cf6]  
[2020-11-19 12:16:30,055: INFO/MainProcess] core.tasks.every_10_sec[ec3b26f3-b469-4caf-9437-d8aba0ba8cf6]: Run every 10sec methods
[2020-11-19 12:16:30,055: INFO/MainProcess] core.tasks.every_10_sec[ec3b26f3-b469-4caf-9437-d8aba0ba8cf6]: result: 73
[2020-11-19 12:16:30,056: INFO/MainProcess] Task core.tasks.every_10_sec[ec3b26f3-b469-4caf-9437-d8aba0ba8cf6] succeeded in 0.0009028000058606267s: 73
[2020-11-19 12:16:30,058: INFO/MainProcess] Received task: core.tasks.every_30_sec[0a7ab774-cc15-41ed-9f71-722e9537c63b]  
[2020-11-19 12:16:30,058: INFO/MainProcess] core.tasks.every_30_sec[0a7ab774-cc15-41ed-9f71-722e9537c63b]: Run every 30sec methods
[2020-11-19 12:16:30,059: INFO/MainProcess] core.tasks.every_30_sec[0a7ab774-cc15-41ed-9f71-722e9537c63b]: result: 390
[2020-11-19 12:16:30,059: INFO/MainProcess] Task core.tasks.every_30_sec[0a7ab774-cc15-41ed-9f71-722e9537c63b] succeeded in 0.000830000004498288s: 390
[2020-11-19 12:16:30,061: INFO/MainProcess] Received task: core.tasks.every_10_sec[ab0feffa-003f-4328-bc89-f27b82d24c74]  
[2020-11-19 12:16:30,062: INFO/MainProcess] core.tasks.every_10_sec[ab0feffa-003f-4328-bc89-f27b82d24c74]: Run every 10sec methods
[2020-11-19 12:16:30,062: INFO/MainProcess] core.tasks.every_10_sec[ab0feffa-003f-4328-bc89-f27b82d24c74]: result: 100
[2020-11-19 12:16:30,062: INFO/MainProcess] Task core.tasks.every_10_sec[ab0feffa-003f-4328-bc89-f27b82d24c74] succeeded in 0.0008095000084722415s: 100
[2020-11-19 12:16:30,064: INFO/MainProcess] Received task: core.tasks.every_10_sec[6fe684bd-4b3a-409d-9386-33bac11b152c]  
[2020-11-19 12:16:30,064: INFO/MainProcess] core.tasks.every_10_sec[6fe684bd-4b3a-409d-9386-33bac11b152c]: Run every 10sec methods
[2020-11-19 12:16:30,065: INFO/MainProcess] core.tasks.every_10_sec[6fe684bd-4b3a-409d-9386-33bac11b152c]: result: 92
[2020-11-19 12:16:30,065: INFO/MainProcess] Task core.tasks.every_10_sec[6fe684bd-4b3a-409d-9386-33bac11b152c] succeeded in 0.0007526999979745597s: 92
[2020-11-19 12:16:30,067: INFO/MainProcess] Received task: core.tasks.every_10_sec[25ca7038-b4e9-4408-98b7-d097fad29d1d]  
[2020-11-19 12:16:30,067: INFO/MainProcess] core.tasks.every_10_sec[25ca7038-b4e9-4408-98b7-d097fad29d1d]: Run every 10sec methods
[2020-11-19 12:16:30,068: INFO/MainProcess] core.tasks.every_10_sec[25ca7038-b4e9-4408-98b7-d097fad29d1d]: result: 146
[2020-11-19 12:16:30,068: INFO/MainProcess] Task core.tasks.every_10_sec[25ca7038-b4e9-4408-98b7-d097fad29d1d] succeeded in 0.0008282000053441152s: 146
[2020-11-19 12:16:30,070: INFO/MainProcess] Received task: core.tasks.every_30_sec[0c932d02-c00a-437c-b8c6-a306e4f1d039]  
[2020-11-19 12:16:30,070: INFO/MainProcess] core.tasks.every_30_sec[0c932d02-c00a-437c-b8c6-a306e4f1d039]: Run every 30sec methods
[2020-11-19 12:16:30,071: INFO/MainProcess] core.tasks.every_30_sec[0c932d02-c00a-437c-b8c6-a306e4f1d039]: result: 326
[2020-11-19 12:16:30,071: INFO/MainProcess] Task core.tasks.every_30_sec[0c932d02-c00a-437c-b8c6-a306e4f1d039] succeeded in 0.0007365000055870041s: 326
[2020-11-19 12:16:30,073: INFO/MainProcess] Received task: core.tasks.every_60_sec[b8563084-4129-4a48-9233-fdd3dfd3eced]  
[2020-11-19 12:16:30,073: INFO/MainProcess] core.tasks.every_60_sec[b8563084-4129-4a48-9233-fdd3dfd3eced]: Run every 60sec methods
[2020-11-19 12:16:30,074: INFO/MainProcess] core.tasks.every_60_sec[b8563084-4129-4a48-9233-fdd3dfd3eced]: result: 734
[2020-11-19 12:16:30,074: INFO/MainProcess] Task core.tasks.every_60_sec[b8563084-4129-4a48-9233-fdd3dfd3eced] succeeded in 0.0009714000043459237s: 734
[2020-11-19 12:16:30,076: INFO/MainProcess] Received task: core.tasks.every_10_sec[0e7bd45b-e8f4-4bb3-aef2-d14e13d8b565]  
[2020-11-19 12:16:30,077: INFO/MainProcess] core.tasks.every_10_sec[0e7bd45b-e8f4-4bb3-aef2-d14e13d8b565]: Run every 10sec methods
[2020-11-19 12:16:30,077: INFO/MainProcess] core.tasks.every_10_sec[0e7bd45b-e8f4-4bb3-aef2-d14e13d8b565]: result: 97
[2020-11-19 12:16:30,077: INFO/MainProcess] Task core.tasks.every_10_sec[0e7bd45b-e8f4-4bb3-aef2-d14e13d8b565] succeeded in 0.0007763000030536205s: 97
[2020-11-19 12:16:30,079: INFO/MainProcess] Received task: core.tasks.every_10_sec[d14c7804-6fdb-45ff-a6dc-c82f9894a9ad]  
[2020-11-19 12:16:30,080: INFO/MainProcess] core.tasks.every_10_sec[d14c7804-6fdb-45ff-a6dc-c82f9894a9ad]: Run every 10sec methods
[2020-11-19 12:16:30,080: INFO/MainProcess] core.tasks.every_10_sec[d14c7804-6fdb-45ff-a6dc-c82f9894a9ad]: result: 44
[2020-11-19 12:16:30,080: INFO/MainProcess] Task core.tasks.every_10_sec[d14c7804-6fdb-45ff-a6dc-c82f9894a9ad] succeeded in 0.0008182000019587576s: 44
[2020-11-19 12:16:30,082: INFO/MainProcess] Received task: core.tasks.every_10_sec[c6254b3f-f3fe-47fb-b5c9-77eaba0813d9]  
[2020-11-19 12:16:30,083: INFO/MainProcess] core.tasks.every_10_sec[c6254b3f-f3fe-47fb-b5c9-77eaba0813d9]: Run every 10sec methods
[2020-11-19 12:16:30,083: INFO/MainProcess] core.tasks.every_10_sec[c6254b3f-f3fe-47fb-b5c9-77eaba0813d9]: result: 81
[2020-11-19 12:16:30,083: INFO/MainProcess] Task core.tasks.every_10_sec[c6254b3f-f3fe-47fb-b5c9-77eaba0813d9] succeeded in 0.0007618999952683225s: 81
[2020-11-19 12:16:30,085: INFO/MainProcess] Received task: core.tasks.every_30_sec[090da4bf-1336-4993-a28b-cf063207889c]  
[2020-11-19 12:16:30,086: INFO/MainProcess] core.tasks.every_30_sec[090da4bf-1336-4993-a28b-cf063207889c]: Run every 30sec methods
[2020-11-19 12:16:30,086: INFO/MainProcess] core.tasks.every_30_sec[090da4bf-1336-4993-a28b-cf063207889c]: result: 359
[2020-11-19 12:16:30,087: INFO/MainProcess] Task core.tasks.every_30_sec[090da4bf-1336-4993-a28b-cf063207889c] succeeded in 0.0009184999944409356s: 359
[2020-11-19 12:16:30,088: INFO/MainProcess] Received task: core.tasks.every_10_sec[930a97f1-a824-4db8-9918-9a860fd94c23]  
[2020-11-19 12:16:30,089: INFO/MainProcess] core.tasks.every_10_sec[930a97f1-a824-4db8-9918-9a860fd94c23]: Run every 10sec methods
[2020-11-19 12:16:30,090: INFO/MainProcess] core.tasks.every_10_sec[930a97f1-a824-4db8-9918-9a860fd94c23]: result: 94
[2020-11-19 12:16:30,090: INFO/MainProcess] Task core.tasks.every_10_sec[930a97f1-a824-4db8-9918-9a860fd94c23] succeeded in 0.0009911999950418249s: 94
[2020-11-19 12:16:30,092: INFO/MainProcess] Received task: core.tasks.every_10_sec[6b66dcf0-e1f0-46ca-ae0f-b94aa33fa526]  
[2020-11-19 12:16:30,093: INFO/MainProcess] core.tasks.every_10_sec[6b66dcf0-e1f0-46ca-ae0f-b94aa33fa526]: Run every 10sec methods
[2020-11-19 12:16:30,093: INFO/MainProcess] core.tasks.every_10_sec[6b66dcf0-e1f0-46ca-ae0f-b94aa33fa526]: result: 106
[2020-11-19 12:16:30,094: INFO/MainProcess] Task core.tasks.every_10_sec[6b66dcf0-e1f0-46ca-ae0f-b94aa33fa526] succeeded in 0.000857999999425374s: 106
[2020-11-19 12:16:30,095: INFO/MainProcess] Received task: core.tasks.every_10_sec[92a97609-2827-4e75-96e6-f5e80f61504e]  
[2020-11-19 12:16:30,096: INFO/MainProcess] core.tasks.every_10_sec[92a97609-2827-4e75-96e6-f5e80f61504e]: Run every 10sec methods
[2020-11-19 12:16:30,096: INFO/MainProcess] core.tasks.every_10_sec[92a97609-2827-4e75-96e6-f5e80f61504e]: result: 120
[2020-11-19 12:16:30,097: INFO/MainProcess] Task core.tasks.every_10_sec[92a97609-2827-4e75-96e6-f5e80f61504e] succeeded in 0.0007947999984025955s: 120
[2020-11-19 12:16:30,098: INFO/MainProcess] Received task: core.tasks.every_30_sec[36e061ad-81ec-40df-8b52-2dc511c96b17]  
[2020-11-19 12:16:30,099: INFO/MainProcess] core.tasks.every_30_sec[36e061ad-81ec-40df-8b52-2dc511c96b17]: Run every 30sec methods
[2020-11-19 12:16:30,099: INFO/MainProcess] core.tasks.every_30_sec[36e061ad-81ec-40df-8b52-2dc511c96b17]: result: 409
[2020-11-19 12:16:30,100: INFO/MainProcess] Task core.tasks.every_30_sec[36e061ad-81ec-40df-8b52-2dc511c96b17] succeeded in 0.0007411999977193773s: 409
[2020-11-19 12:16:30,101: INFO/MainProcess] Received task: core.tasks.every_60_sec[2f56d402-9670-4b3d-841c-1a16a6688629]  
[2020-11-19 12:16:30,102: INFO/MainProcess] core.tasks.every_60_sec[2f56d402-9670-4b3d-841c-1a16a6688629]: Run every 60sec methods
[2020-11-19 12:16:30,102: INFO/MainProcess] core.tasks.every_60_sec[2f56d402-9670-4b3d-841c-1a16a6688629]: result: 783
[2020-11-19 12:16:30,103: INFO/MainProcess] Task core.tasks.every_60_sec[2f56d402-9670-4b3d-841c-1a16a6688629] succeeded in 0.0007337999995797873s: 783
[2020-11-19 12:16:30,104: INFO/MainProcess] Received task: core.tasks.every_10_sec[3b05e5df-ca54-4f27-a920-c5dbea1974b0]  
[2020-11-19 12:16:30,105: INFO/MainProcess] core.tasks.every_10_sec[3b05e5df-ca54-4f27-a920-c5dbea1974b0]: Run every 10sec methods
[2020-11-19 12:16:30,105: INFO/MainProcess] core.tasks.every_10_sec[3b05e5df-ca54-4f27-a920-c5dbea1974b0]: result: 168
[2020-11-19 12:16:30,105: INFO/MainProcess] Task core.tasks.every_10_sec[3b05e5df-ca54-4f27-a920-c5dbea1974b0] succeeded in 0.0007535999902756885s: 168
[2020-11-19 12:16:30,108: INFO/MainProcess] Received task: core.tasks.every_10_sec[176b330d-c2bb-45e7-8df2-817dbc65b672]  
[2020-11-19 12:16:30,108: INFO/MainProcess] core.tasks.every_10_sec[176b330d-c2bb-45e7-8df2-817dbc65b672]: Run every 10sec methods
[2020-11-19 12:16:30,109: INFO/MainProcess] core.tasks.every_10_sec[176b330d-c2bb-45e7-8df2-817dbc65b672]: result: 128
[2020-11-19 12:16:30,109: INFO/MainProcess] Task core.tasks.every_10_sec[176b330d-c2bb-45e7-8df2-817dbc65b672] succeeded in 0.0009080999880097806s: 128
[2020-11-19 12:16:30,111: INFO/MainProcess] Received task: core.tasks.every_10_sec[0478fcda-4835-48c6-82e9-6cbbcf7998aa]  
[2020-11-19 12:16:30,111: INFO/MainProcess] core.tasks.every_10_sec[0478fcda-4835-48c6-82e9-6cbbcf7998aa]: Run every 10sec methods
[2020-11-19 12:16:30,112: INFO/MainProcess] core.tasks.every_10_sec[0478fcda-4835-48c6-82e9-6cbbcf7998aa]: result: 86
[2020-11-19 12:16:30,112: INFO/MainProcess] Task core.tasks.every_10_sec[0478fcda-4835-48c6-82e9-6cbbcf7998aa] succeeded in 0.0007392999978037551s: 86
[2020-11-19 12:16:30,114: INFO/MainProcess] Received task: core.tasks.every_30_sec[3e6a6350-e9e9-4b28-be73-f310e8807c4f]  
[2020-11-19 12:16:30,114: INFO/MainProcess] core.tasks.every_30_sec[3e6a6350-e9e9-4b28-be73-f310e8807c4f]: Run every 30sec methods
[2020-11-19 12:16:30,115: INFO/MainProcess] core.tasks.every_30_sec[3e6a6350-e9e9-4b28-be73-f310e8807c4f]: result: 348
[2020-11-19 12:16:30,115: INFO/MainProcess] Task core.tasks.every_30_sec[3e6a6350-e9e9-4b28-be73-f310e8807c4f] succeeded in 0.0007533000025432557s: 348
[2020-11-19 12:16:30,117: INFO/MainProcess] Received task: core.tasks.every_10_sec[fed95e76-586e-4e23-bade-c2f0f7c62562]  
[2020-11-19 12:16:30,117: INFO/MainProcess] core.tasks.every_10_sec[fed95e76-586e-4e23-bade-c2f0f7c62562]: Run every 10sec methods
[2020-11-19 12:16:30,117: INFO/MainProcess] core.tasks.every_10_sec[fed95e76-586e-4e23-bade-c2f0f7c62562]: result: 112
[2020-11-19 12:16:30,118: INFO/MainProcess] Task core.tasks.every_10_sec[fed95e76-586e-4e23-bade-c2f0f7c62562] succeeded in 0.0007679999980609864s: 112
[2020-11-19 12:16:30,120: INFO/MainProcess] Received task: core.tasks.every_10_sec[58b968eb-e520-4128-9df4-da21520b3692]  
[2020-11-19 12:16:30,120: INFO/MainProcess] core.tasks.every_10_sec[58b968eb-e520-4128-9df4-da21520b3692]: Run every 10sec methods
[2020-11-19 12:16:30,120: INFO/MainProcess] core.tasks.every_10_sec[58b968eb-e520-4128-9df4-da21520b3692]: result: 129
[2020-11-19 12:16:30,121: INFO/MainProcess] Task core.tasks.every_10_sec[58b968eb-e520-4128-9df4-da21520b3692] succeeded in 0.0007585999992443249s: 129
[2020-11-19 12:16:30,122: INFO/MainProcess] Received task: core.tasks.every_10_sec[18bcc510-5b86-46d9-97ed-76e2242a3604]  
[2020-11-19 12:16:30,123: INFO/MainProcess] core.tasks.every_10_sec[18bcc510-5b86-46d9-97ed-76e2242a3604]: Run every 10sec methods
[2020-11-19 12:16:30,123: INFO/MainProcess] core.tasks.every_10_sec[18bcc510-5b86-46d9-97ed-76e2242a3604]: result: 57
[2020-11-19 12:16:30,124: INFO/MainProcess] Task core.tasks.every_10_sec[18bcc510-5b86-46d9-97ed-76e2242a3604] succeeded in 0.000945399995543994s: 57
[2020-11-19 12:16:30,126: INFO/MainProcess] Received task: core.tasks.every_30_sec[57a09b9d-b623-42fe-bb8d-2a0730929dbd]  
[2020-11-19 12:16:30,126: INFO/MainProcess] core.tasks.every_30_sec[57a09b9d-b623-42fe-bb8d-2a0730929dbd]: Run every 30sec methods
[2020-11-19 12:16:30,127: INFO/MainProcess] core.tasks.every_30_sec[57a09b9d-b623-42fe-bb8d-2a0730929dbd]: result: 389
[2020-11-19 12:16:30,127: INFO/MainProcess] Task core.tasks.every_30_sec[57a09b9d-b623-42fe-bb8d-2a0730929dbd] succeeded in 0.0008096999954432249s: 389
[2020-11-19 12:16:30,129: INFO/MainProcess] Received task: core.tasks.every_60_sec[6fd7e778-d10c-4dce-b7f4-52fe88227195]  
[2020-11-19 12:16:30,129: INFO/MainProcess] core.tasks.every_60_sec[6fd7e778-d10c-4dce-b7f4-52fe88227195]: Run every 60sec methods
[2020-11-19 12:16:30,130: INFO/MainProcess] core.tasks.every_60_sec[6fd7e778-d10c-4dce-b7f4-52fe88227195]: result: 796
[2020-11-19 12:16:30,130: INFO/MainProcess] Task core.tasks.every_60_sec[6fd7e778-d10c-4dce-b7f4-52fe88227195] succeeded in 0.0007717999978922307s: 796
[2020-11-19 12:16:30,132: INFO/MainProcess] Received task: core.tasks.every_10_sec[f30cf63c-6f92-4198-ab75-2e88d0bf414a]  
[2020-11-19 12:16:30,132: INFO/MainProcess] core.tasks.every_10_sec[f30cf63c-6f92-4198-ab75-2e88d0bf414a]: Run every 10sec methods
[2020-11-19 12:16:30,133: INFO/MainProcess] core.tasks.every_10_sec[f30cf63c-6f92-4198-ab75-2e88d0bf414a]: result: 114
[2020-11-19 12:16:30,133: INFO/MainProcess] Task core.tasks.every_10_sec[f30cf63c-6f92-4198-ab75-2e88d0bf414a] succeeded in 0.0008342000073753297s: 114
[2020-11-19 12:16:30,135: INFO/MainProcess] Received task: core.tasks.every_10_sec[14bd76a2-d85f-4316-84a3-6306298b4bb0]  
[2020-11-19 12:16:30,135: INFO/MainProcess] core.tasks.every_10_sec[14bd76a2-d85f-4316-84a3-6306298b4bb0]: Run every 10sec methods
[2020-11-19 12:16:30,136: INFO/MainProcess] core.tasks.every_10_sec[14bd76a2-d85f-4316-84a3-6306298b4bb0]: result: 154
[2020-11-19 12:16:30,136: INFO/MainProcess] Task core.tasks.every_10_sec[14bd76a2-d85f-4316-84a3-6306298b4bb0] succeeded in 0.0007448999967891723s: 154
[2020-11-19 12:16:30,138: INFO/MainProcess] Received task: core.tasks.every_10_sec[14df9aaf-ef72-4b25-9eb0-9042647d8a1a]  
[2020-11-19 12:16:30,138: INFO/MainProcess] core.tasks.every_10_sec[14df9aaf-ef72-4b25-9eb0-9042647d8a1a]: Run every 10sec methods
[2020-11-19 12:16:30,138: INFO/MainProcess] core.tasks.every_10_sec[14df9aaf-ef72-4b25-9eb0-9042647d8a1a]: result: 55
[2020-11-19 12:16:30,139: INFO/MainProcess] Task core.tasks.every_10_sec[14df9aaf-ef72-4b25-9eb0-9042647d8a1a] succeeded in 0.000768100013374351s: 55
[2020-11-19 12:16:30,141: INFO/MainProcess] Received task: core.tasks.every_30_sec[6fdc1804-11b9-4872-bc28-9b7cde292c90]  
[2020-11-19 12:16:30,142: INFO/MainProcess] core.tasks.every_30_sec[6fdc1804-11b9-4872-bc28-9b7cde292c90]: Run every 30sec methods
[2020-11-19 12:16:30,142: INFO/MainProcess] core.tasks.every_30_sec[6fdc1804-11b9-4872-bc28-9b7cde292c90]: result: 422
[2020-11-19 12:16:30,142: INFO/MainProcess] Task core.tasks.every_30_sec[6fdc1804-11b9-4872-bc28-9b7cde292c90] succeeded in 0.0008383999957004562s: 422
[2020-11-19 12:16:30,144: INFO/MainProcess] Received task: core.tasks.every_10_sec[ef8b3c8d-ab4d-4d3e-939d-38ccab933040]  
[2020-11-19 12:16:30,144: INFO/MainProcess] core.tasks.every_10_sec[ef8b3c8d-ab4d-4d3e-939d-38ccab933040]: Run every 10sec methods
[2020-11-19 12:16:30,145: INFO/MainProcess] core.tasks.every_10_sec[ef8b3c8d-ab4d-4d3e-939d-38ccab933040]: result: 15
[2020-11-19 12:16:30,145: INFO/MainProcess] Task core.tasks.every_10_sec[ef8b3c8d-ab4d-4d3e-939d-38ccab933040] succeeded in 0.0007839000027161092s: 15
[2020-11-19 12:16:30,147: INFO/MainProcess] Received task: core.tasks.every_10_sec[1a470eff-18fb-4546-9cab-65f3b5f2a16f]  
[2020-11-19 12:16:30,147: INFO/MainProcess] core.tasks.every_10_sec[1a470eff-18fb-4546-9cab-65f3b5f2a16f]: Run every 10sec methods
[2020-11-19 12:16:30,148: INFO/MainProcess] core.tasks.every_10_sec[1a470eff-18fb-4546-9cab-65f3b5f2a16f]: result: 150
[2020-11-19 12:16:30,148: INFO/MainProcess] Task core.tasks.every_10_sec[1a470eff-18fb-4546-9cab-65f3b5f2a16f] succeeded in 0.0007666000019526109s: 150
[2020-11-19 12:16:30,150: INFO/MainProcess] Received task: core.tasks.every_10_sec[07df04bf-d861-4613-83f7-29fe9b4e1bf3]  
[2020-11-19 12:16:30,150: INFO/MainProcess] core.tasks.every_10_sec[07df04bf-d861-4613-83f7-29fe9b4e1bf3]: Run every 10sec methods
[2020-11-19 12:16:30,151: INFO/MainProcess] core.tasks.every_10_sec[07df04bf-d861-4613-83f7-29fe9b4e1bf3]: result: 26
[2020-11-19 12:16:30,151: INFO/MainProcess] Task core.tasks.every_10_sec[07df04bf-d861-4613-83f7-29fe9b4e1bf3] succeeded in 0.0007766000053379685s: 26
[2020-11-19 12:16:30,153: INFO/MainProcess] Received task: core.tasks.every_30_sec[fe6e624b-8619-41b5-8604-36437381511d]  
[2020-11-19 12:16:30,153: INFO/MainProcess] core.tasks.every_30_sec[fe6e624b-8619-41b5-8604-36437381511d]: Run every 30sec methods
[2020-11-19 12:16:30,154: INFO/MainProcess] core.tasks.every_30_sec[fe6e624b-8619-41b5-8604-36437381511d]: result: 347
[2020-11-19 12:16:30,154: INFO/MainProcess] Task core.tasks.every_30_sec[fe6e624b-8619-41b5-8604-36437381511d] succeeded in 0.0007337999995797873s: 347
[2020-11-19 12:16:30,156: INFO/MainProcess] Received task: core.tasks.every_60_sec[bd7d44ca-4417-4702-8f0a-ff2bceb9d081]  
[2020-11-19 12:16:30,157: INFO/MainProcess] core.tasks.every_60_sec[bd7d44ca-4417-4702-8f0a-ff2bceb9d081]: Run every 60sec methods
[2020-11-19 12:16:30,157: INFO/MainProcess] core.tasks.every_60_sec[bd7d44ca-4417-4702-8f0a-ff2bceb9d081]: result: 725
[2020-11-19 12:16:30,158: INFO/MainProcess] Task core.tasks.every_60_sec[bd7d44ca-4417-4702-8f0a-ff2bceb9d081] succeeded in 0.0010959000064758584s: 725
[2020-11-19 12:16:30,160: INFO/MainProcess] Received task: core.tasks.every_10_sec[f0d86e53-508a-4a50-a783-53e0c15ce476]  
[2020-11-19 12:16:30,160: INFO/MainProcess] core.tasks.every_10_sec[f0d86e53-508a-4a50-a783-53e0c15ce476]: Run every 10sec methods
[2020-11-19 12:16:30,160: INFO/MainProcess] core.tasks.every_10_sec[f0d86e53-508a-4a50-a783-53e0c15ce476]: result: 122
[2020-11-19 12:16:30,161: INFO/MainProcess] Task core.tasks.every_10_sec[f0d86e53-508a-4a50-a783-53e0c15ce476] succeeded in 0.0007973000028869137s: 122
[2020-11-19 12:16:30,162: INFO/MainProcess] Received task: core.tasks.every_10_sec[d13e92a2-9dd2-4fbb-911e-31f8d59d3d2e]  
[2020-11-19 12:16:30,163: INFO/MainProcess] core.tasks.every_10_sec[d13e92a2-9dd2-4fbb-911e-31f8d59d3d2e]: Run every 10sec methods
[2020-11-19 12:16:30,163: INFO/MainProcess] core.tasks.every_10_sec[d13e92a2-9dd2-4fbb-911e-31f8d59d3d2e]: result: 33
[2020-11-19 12:16:30,164: INFO/MainProcess] Task core.tasks.every_10_sec[d13e92a2-9dd2-4fbb-911e-31f8d59d3d2e] succeeded in 0.0007580999954370782s: 33
[2020-11-19 12:16:30,165: INFO/MainProcess] Received task: core.tasks.every_10_sec[668cd558-8133-4999-82e7-82c22e722243]  
[2020-11-19 12:16:30,166: INFO/MainProcess] core.tasks.every_10_sec[668cd558-8133-4999-82e7-82c22e722243]: Run every 10sec methods
[2020-11-19 12:16:30,166: INFO/MainProcess] core.tasks.every_10_sec[668cd558-8133-4999-82e7-82c22e722243]: result: 110
[2020-11-19 12:16:30,167: INFO/MainProcess] Task core.tasks.every_10_sec[668cd558-8133-4999-82e7-82c22e722243] succeeded in 0.0007499000057578087s: 110
[2020-11-19 12:16:30,168: INFO/MainProcess] Received task: core.tasks.every_30_sec[e667bf81-7284-4421-9fd3-5336010064cc]  
[2020-11-19 12:16:30,169: INFO/MainProcess] core.tasks.every_30_sec[e667bf81-7284-4421-9fd3-5336010064cc]: Run every 30sec methods
[2020-11-19 12:16:30,169: INFO/MainProcess] core.tasks.every_30_sec[e667bf81-7284-4421-9fd3-5336010064cc]: result: 410
[2020-11-19 12:16:30,169: INFO/MainProcess] Task core.tasks.every_30_sec[e667bf81-7284-4421-9fd3-5336010064cc] succeeded in 0.0007838000019546598s: 410
[2020-11-19 12:16:30,171: INFO/MainProcess] Received task: core.tasks.every_10_sec[8b328ac7-816a-461e-9d3d-524c7416d550]  
[2020-11-19 12:16:30,172: INFO/MainProcess] core.tasks.every_10_sec[8b328ac7-816a-461e-9d3d-524c7416d550]: Run every 10sec methods
[2020-11-19 12:16:30,172: INFO/MainProcess] core.tasks.every_10_sec[8b328ac7-816a-461e-9d3d-524c7416d550]: result: 157
[2020-11-19 12:16:30,172: INFO/MainProcess] Task core.tasks.every_10_sec[8b328ac7-816a-461e-9d3d-524c7416d550] succeeded in 0.0008477999945171177s: 157
[2020-11-19 12:16:30,174: INFO/MainProcess] Received task: core.tasks.every_10_sec[008f49a4-5126-49b3-8f4d-2441eef600e3]  
[2020-11-19 12:16:30,175: INFO/MainProcess] core.tasks.every_10_sec[008f49a4-5126-49b3-8f4d-2441eef600e3]: Run every 10sec methods
[2020-11-19 12:16:30,175: INFO/MainProcess] core.tasks.every_10_sec[008f49a4-5126-49b3-8f4d-2441eef600e3]: result: 191
[2020-11-19 12:16:30,176: INFO/MainProcess] Task core.tasks.every_10_sec[008f49a4-5126-49b3-8f4d-2441eef600e3] succeeded in 0.0008121999999275431s: 191
[2020-11-19 12:16:30,177: INFO/MainProcess] Received task: core.tasks.every_10_sec[8edb7293-9ea8-4eeb-ae8b-fc0397405044]  
[2020-11-19 12:16:30,178: INFO/MainProcess] core.tasks.every_10_sec[8edb7293-9ea8-4eeb-ae8b-fc0397405044]: Run every 10sec methods
[2020-11-19 12:16:30,178: INFO/MainProcess] core.tasks.every_10_sec[8edb7293-9ea8-4eeb-ae8b-fc0397405044]: result: 130
[2020-11-19 12:16:30,179: INFO/MainProcess] Task core.tasks.every_10_sec[8edb7293-9ea8-4eeb-ae8b-fc0397405044] succeeded in 0.0007624999998370185s: 130
[2020-11-19 12:16:30,180: INFO/MainProcess] Received task: core.tasks.every_30_sec[8c9e984c-1495-489d-9759-18a435cf7c1f]  
[2020-11-19 12:16:30,181: INFO/MainProcess] core.tasks.every_30_sec[8c9e984c-1495-489d-9759-18a435cf7c1f]: Run every 30sec methods
[2020-11-19 12:16:30,181: INFO/MainProcess] core.tasks.every_30_sec[8c9e984c-1495-489d-9759-18a435cf7c1f]: result: 363
[2020-11-19 12:16:30,181: INFO/MainProcess] Task core.tasks.every_30_sec[8c9e984c-1495-489d-9759-18a435cf7c1f] succeeded in 0.0007609000022057444s: 363
[2020-11-19 12:16:30,183: INFO/MainProcess] Received task: core.tasks.every_60_sec[e40af1cf-c9a4-4463-bb93-2ca50132a471]  
[2020-11-19 12:16:30,184: INFO/MainProcess] core.tasks.every_60_sec[e40af1cf-c9a4-4463-bb93-2ca50132a471]: Run every 60sec methods
[2020-11-19 12:16:30,184: INFO/MainProcess] core.tasks.every_60_sec[e40af1cf-c9a4-4463-bb93-2ca50132a471]: result: 830
[2020-11-19 12:16:30,184: INFO/MainProcess] Task core.tasks.every_60_sec[e40af1cf-c9a4-4463-bb93-2ca50132a471] succeeded in 0.0007449999975506216s: 830
[2020-11-19 12:16:30,186: INFO/MainProcess] Received task: core.tasks.every_10_sec[076f225f-f41f-43c9-87ca-03631f625330]  
[2020-11-19 12:16:30,186: INFO/MainProcess] core.tasks.every_10_sec[076f225f-f41f-43c9-87ca-03631f625330]: Run every 10sec methods
[2020-11-19 12:16:30,187: INFO/MainProcess] core.tasks.every_10_sec[076f225f-f41f-43c9-87ca-03631f625330]: result: 138
[2020-11-19 12:16:30,187: INFO/MainProcess] Task core.tasks.every_10_sec[076f225f-f41f-43c9-87ca-03631f625330] succeeded in 0.0007402000046567991s: 138
[2020-11-19 12:16:30,189: INFO/MainProcess] Received task: core.tasks.every_10_sec[d24d9e75-c157-4c3d-8a71-f255c98fcecc]  
[2020-11-19 12:16:30,189: INFO/MainProcess] core.tasks.every_10_sec[d24d9e75-c157-4c3d-8a71-f255c98fcecc]: Run every 10sec methods
[2020-11-19 12:16:30,190: INFO/MainProcess] core.tasks.every_10_sec[d24d9e75-c157-4c3d-8a71-f255c98fcecc]: result: 179
[2020-11-19 12:16:30,190: INFO/MainProcess] Task core.tasks.every_10_sec[d24d9e75-c157-4c3d-8a71-f255c98fcecc] succeeded in 0.0008214999979827553s: 179
[2020-11-19 12:16:30,192: INFO/MainProcess] Received task: core.tasks.every_10_sec[0e1d0d26-fbea-486a-a49b-87424abbe41b]  
[2020-11-19 12:16:30,192: INFO/MainProcess] core.tasks.every_10_sec[0e1d0d26-fbea-486a-a49b-87424abbe41b]: Run every 10sec methods
[2020-11-19 12:16:30,193: INFO/MainProcess] core.tasks.every_10_sec[0e1d0d26-fbea-486a-a49b-87424abbe41b]: result: 122
[2020-11-19 12:16:30,193: INFO/MainProcess] Task core.tasks.every_10_sec[0e1d0d26-fbea-486a-a49b-87424abbe41b] succeeded in 0.0007402999908663332s: 122
[2020-11-19 12:16:30,195: INFO/MainProcess] Received task: core.tasks.every_30_sec[718d228e-8744-40c8-bd17-9808eb7b9905]  
[2020-11-19 12:16:30,195: INFO/MainProcess] core.tasks.every_30_sec[718d228e-8744-40c8-bd17-9808eb7b9905]: Run every 30sec methods
[2020-11-19 12:16:30,196: INFO/MainProcess] core.tasks.every_30_sec[718d228e-8744-40c8-bd17-9808eb7b9905]: result: 429
[2020-11-19 12:16:30,196: INFO/MainProcess] Task core.tasks.every_30_sec[718d228e-8744-40c8-bd17-9808eb7b9905] succeeded in 0.0007237999961944297s: 429
[2020-11-19 12:16:30,198: INFO/MainProcess] Received task: core.tasks.every_10_sec[266e4a86-5717-4e16-84d4-be475243bf61]  
[2020-11-19 12:16:30,198: INFO/MainProcess] core.tasks.every_10_sec[266e4a86-5717-4e16-84d4-be475243bf61]: Run every 10sec methods
[2020-11-19 12:16:30,198: INFO/MainProcess] core.tasks.every_10_sec[266e4a86-5717-4e16-84d4-be475243bf61]: result: 72
[2020-11-19 12:16:30,199: INFO/MainProcess] Task core.tasks.every_10_sec[266e4a86-5717-4e16-84d4-be475243bf61] succeeded in 0.0007628999883309007s: 72
[2020-11-19 12:16:30,201: INFO/MainProcess] Received task: core.tasks.every_10_sec[16cf9cd0-17a3-4cd2-8a58-770774274678]  
[2020-11-19 12:16:30,201: INFO/MainProcess] core.tasks.every_10_sec[16cf9cd0-17a3-4cd2-8a58-770774274678]: Run every 10sec methods
[2020-11-19 12:16:30,201: INFO/MainProcess] core.tasks.every_10_sec[16cf9cd0-17a3-4cd2-8a58-770774274678]: result: 45
[2020-11-19 12:16:30,202: INFO/MainProcess] Task core.tasks.every_10_sec[16cf9cd0-17a3-4cd2-8a58-770774274678] succeeded in 0.0007442999922204763s: 45
[2020-11-19 12:16:30,203: INFO/MainProcess] Received task: core.tasks.every_10_sec[7ae7e2f4-3089-4221-802b-21579a491c44]  
[2020-11-19 12:16:30,204: INFO/MainProcess] core.tasks.every_10_sec[7ae7e2f4-3089-4221-802b-21579a491c44]: Run every 10sec methods
[2020-11-19 12:16:30,204: INFO/MainProcess] core.tasks.every_10_sec[7ae7e2f4-3089-4221-802b-21579a491c44]: result: 107
[2020-11-19 12:16:30,205: INFO/MainProcess] Task core.tasks.every_10_sec[7ae7e2f4-3089-4221-802b-21579a491c44] succeeded in 0.0007485999958589673s: 107
[2020-11-19 12:16:30,206: INFO/MainProcess] Received task: core.tasks.every_30_sec[9d9a57ea-b1d3-42d9-83ab-d9b23aab5cf0]  
[2020-11-19 12:16:30,207: INFO/MainProcess] core.tasks.every_30_sec[9d9a57ea-b1d3-42d9-83ab-d9b23aab5cf0]: Run every 30sec methods
[2020-11-19 12:16:30,207: INFO/MainProcess] core.tasks.every_30_sec[9d9a57ea-b1d3-42d9-83ab-d9b23aab5cf0]: result: 349
[2020-11-19 12:16:30,208: INFO/MainProcess] Task core.tasks.every_30_sec[9d9a57ea-b1d3-42d9-83ab-d9b23aab5cf0] succeeded in 0.0010094999888679013s: 349
[2020-11-19 12:16:30,210: INFO/MainProcess] Received task: core.tasks.every_60_sec[ee78226e-04bd-4cf7-8edd-588a494baa37]  
[2020-11-19 12:16:30,211: INFO/MainProcess] core.tasks.every_60_sec[ee78226e-04bd-4cf7-8edd-588a494baa37]: Run every 60sec methods
[2020-11-19 12:16:30,211: INFO/MainProcess] core.tasks.every_60_sec[ee78226e-04bd-4cf7-8edd-588a494baa37]: result: 795
[2020-11-19 12:16:30,212: INFO/MainProcess] Task core.tasks.every_60_sec[ee78226e-04bd-4cf7-8edd-588a494baa37] succeeded in 0.0011295000003883615s: 795
[2020-11-19 12:16:30,214: INFO/MainProcess] Received task: core.tasks.every_10_sec[06663d37-db57-4bbb-b60c-e5c1e7a95639]  
[2020-11-19 12:16:30,214: INFO/MainProcess] core.tasks.every_10_sec[06663d37-db57-4bbb-b60c-e5c1e7a95639]: Run every 10sec methods
[2020-11-19 12:16:30,215: INFO/MainProcess] core.tasks.every_10_sec[06663d37-db57-4bbb-b60c-e5c1e7a95639]: result: 36
[2020-11-19 12:16:30,215: INFO/MainProcess] Task core.tasks.every_10_sec[06663d37-db57-4bbb-b60c-e5c1e7a95639] succeeded in 0.000738000002456829s: 36
[2020-11-19 12:16:30,217: INFO/MainProcess] Received task: core.tasks.every_10_sec[e03a1cec-c511-4b30-9b80-3ee05b224af1]  
[2020-11-19 12:16:30,217: INFO/MainProcess] core.tasks.every_10_sec[e03a1cec-c511-4b30-9b80-3ee05b224af1]: Run every 10sec methods
[2020-11-19 12:16:30,218: INFO/MainProcess] core.tasks.every_10_sec[e03a1cec-c511-4b30-9b80-3ee05b224af1]: result: 82
[2020-11-19 12:16:30,218: INFO/MainProcess] Task core.tasks.every_10_sec[e03a1cec-c511-4b30-9b80-3ee05b224af1] succeeded in 0.000742000003810972s: 82
[2020-11-19 12:16:30,220: INFO/MainProcess] Received task: core.tasks.every_10_sec[6e028722-adc1-4641-8e53-8923f9fb821e]  
[2020-11-19 12:16:30,220: INFO/MainProcess] core.tasks.every_10_sec[6e028722-adc1-4641-8e53-8923f9fb821e]: Run every 10sec methods
[2020-11-19 12:16:30,221: INFO/MainProcess] core.tasks.every_10_sec[6e028722-adc1-4641-8e53-8923f9fb821e]: result: 106
[2020-11-19 12:16:30,221: INFO/MainProcess] Task core.tasks.every_10_sec[6e028722-adc1-4641-8e53-8923f9fb821e] succeeded in 0.0007207000016933307s: 106
[2020-11-19 12:16:30,223: INFO/MainProcess] Received task: core.tasks.every_30_sec[0949efb5-4a53-4a5b-ba9f-0dfaeadea0a0]  
[2020-11-19 12:16:30,223: INFO/MainProcess] core.tasks.every_30_sec[0949efb5-4a53-4a5b-ba9f-0dfaeadea0a0]: Run every 30sec methods
[2020-11-19 12:16:30,224: INFO/MainProcess] core.tasks.every_30_sec[0949efb5-4a53-4a5b-ba9f-0dfaeadea0a0]: result: 472
[2020-11-19 12:16:30,224: INFO/MainProcess] Task core.tasks.every_30_sec[0949efb5-4a53-4a5b-ba9f-0dfaeadea0a0] succeeded in 0.0009265999979106709s: 472
[2020-11-19 12:16:30,226: INFO/MainProcess] Received task: core.tasks.every_10_sec[2fd8cf5e-3004-43b8-8b92-186b51edefd7]  
[2020-11-19 12:16:30,227: INFO/MainProcess] core.tasks.every_10_sec[2fd8cf5e-3004-43b8-8b92-186b51edefd7]: Run every 10sec methods
[2020-11-19 12:16:30,227: INFO/MainProcess] core.tasks.every_10_sec[2fd8cf5e-3004-43b8-8b92-186b51edefd7]: result: 66
[2020-11-19 12:16:30,227: INFO/MainProcess] Task core.tasks.every_10_sec[2fd8cf5e-3004-43b8-8b92-186b51edefd7] succeeded in 0.0007901999924797565s: 66
[2020-11-19 12:16:30,229: INFO/MainProcess] Received task: core.tasks.every_10_sec[09c01f89-6035-4961-bfec-006494e0f3e1]  
[2020-11-19 12:16:30,230: INFO/MainProcess] core.tasks.every_10_sec[09c01f89-6035-4961-bfec-006494e0f3e1]: Run every 10sec methods
[2020-11-19 12:16:30,230: INFO/MainProcess] core.tasks.every_10_sec[09c01f89-6035-4961-bfec-006494e0f3e1]: result: 76
[2020-11-19 12:16:30,230: INFO/MainProcess] Task core.tasks.every_10_sec[09c01f89-6035-4961-bfec-006494e0f3e1] succeeded in 0.0007385000062640756s: 76
[2020-11-19 12:16:30,232: INFO/MainProcess] Received task: core.tasks.every_10_sec[a8183c66-d4cb-423b-a64f-8df9cbff02cb]  
[2020-11-19 12:16:30,232: INFO/MainProcess] core.tasks.every_10_sec[a8183c66-d4cb-423b-a64f-8df9cbff02cb]: Run every 10sec methods
[2020-11-19 12:16:30,233: INFO/MainProcess] core.tasks.every_10_sec[a8183c66-d4cb-423b-a64f-8df9cbff02cb]: result: 153
[2020-11-19 12:16:30,233: INFO/MainProcess] Task core.tasks.every_10_sec[a8183c66-d4cb-423b-a64f-8df9cbff02cb] succeeded in 0.0007256000099005178s: 153
[2020-11-19 12:16:30,235: INFO/MainProcess] Received task: core.tasks.every_30_sec[549a6045-b532-4808-9b30-801357db9011]  
[2020-11-19 12:16:30,235: INFO/MainProcess] core.tasks.every_30_sec[549a6045-b532-4808-9b30-801357db9011]: Run every 30sec methods
[2020-11-19 12:16:30,236: INFO/MainProcess] core.tasks.every_30_sec[549a6045-b532-4808-9b30-801357db9011]: result: 483
[2020-11-19 12:16:30,236: INFO/MainProcess] Task core.tasks.every_30_sec[549a6045-b532-4808-9b30-801357db9011] succeeded in 0.0007264000014401972s: 483
[2020-11-19 12:16:30,238: INFO/MainProcess] Received task: core.tasks.every_60_sec[0716dec9-6861-40c7-bf85-efe9d423e0a3]  
[2020-11-19 12:16:30,238: INFO/MainProcess] core.tasks.every_60_sec[0716dec9-6861-40c7-bf85-efe9d423e0a3]: Run every 60sec methods
[2020-11-19 12:16:30,238: INFO/MainProcess] core.tasks.every_60_sec[0716dec9-6861-40c7-bf85-efe9d423e0a3]: result: 828
[2020-11-19 12:16:30,239: INFO/MainProcess] Task core.tasks.every_60_sec[0716dec9-6861-40c7-bf85-efe9d423e0a3] succeeded in 0.0008275000000139698s: 828
[2020-11-19 12:16:30,241: INFO/MainProcess] Received task: core.tasks.every_10_sec[d50e4123-62e6-4f5e-9c62-df566b37ee2f]  
[2020-11-19 12:16:30,242: INFO/MainProcess] core.tasks.every_10_sec[d50e4123-62e6-4f5e-9c62-df566b37ee2f]: Run every 10sec methods
[2020-11-19 12:16:30,242: INFO/MainProcess] core.tasks.every_10_sec[d50e4123-62e6-4f5e-9c62-df566b37ee2f]: result: 135
[2020-11-19 12:16:30,242: INFO/MainProcess] Task core.tasks.every_10_sec[d50e4123-62e6-4f5e-9c62-df566b37ee2f] succeeded in 0.0008948000031523407s: 135
[2020-11-19 12:16:30,244: INFO/MainProcess] Received task: core.tasks.every_10_sec[0fcb8ba7-7402-4a2e-87e8-402ebc57b3f3]  
[2020-11-19 12:16:30,245: INFO/MainProcess] core.tasks.every_10_sec[0fcb8ba7-7402-4a2e-87e8-402ebc57b3f3]: Run every 10sec methods
[2020-11-19 12:16:30,245: INFO/MainProcess] core.tasks.every_10_sec[0fcb8ba7-7402-4a2e-87e8-402ebc57b3f3]: result: 110
[2020-11-19 12:16:30,245: INFO/MainProcess] Task core.tasks.every_10_sec[0fcb8ba7-7402-4a2e-87e8-402ebc57b3f3] succeeded in 0.0007773000106681138s: 110
[2020-11-19 12:16:30,247: INFO/MainProcess] Received task: core.tasks.every_10_sec[8cd4f175-123f-44de-9eb0-92813f704af7]  
[2020-11-19 12:16:30,248: INFO/MainProcess] core.tasks.every_10_sec[8cd4f175-123f-44de-9eb0-92813f704af7]: Run every 10sec methods
[2020-11-19 12:16:30,248: INFO/MainProcess] core.tasks.every_10_sec[8cd4f175-123f-44de-9eb0-92813f704af7]: result: 77
[2020-11-19 12:16:30,248: INFO/MainProcess] Task core.tasks.every_10_sec[8cd4f175-123f-44de-9eb0-92813f704af7] succeeded in 0.0007350999949267134s: 77
[2020-11-19 12:16:30,250: INFO/MainProcess] Received task: core.tasks.every_30_sec[fc99f9d4-f5f5-4898-932f-8f222eb57b76]  
[2020-11-19 12:16:30,250: INFO/MainProcess] core.tasks.every_30_sec[fc99f9d4-f5f5-4898-932f-8f222eb57b76]: Run every 30sec methods
[2020-11-19 12:16:30,251: INFO/MainProcess] core.tasks.every_30_sec[fc99f9d4-f5f5-4898-932f-8f222eb57b76]: result: 428
[2020-11-19 12:16:30,251: INFO/MainProcess] Task core.tasks.every_30_sec[fc99f9d4-f5f5-4898-932f-8f222eb57b76] succeeded in 0.0007324999896809459s: 428
[2020-11-19 12:16:30,253: INFO/MainProcess] Received task: core.tasks.every_10_sec[13469f46-383a-4f58-bf60-86793d3ca7cb]  
[2020-11-19 12:16:30,253: INFO/MainProcess] core.tasks.every_10_sec[13469f46-383a-4f58-bf60-86793d3ca7cb]: Run every 10sec methods
[2020-11-19 12:16:30,254: INFO/MainProcess] core.tasks.every_10_sec[13469f46-383a-4f58-bf60-86793d3ca7cb]: result: 81
[2020-11-19 12:16:30,254: INFO/MainProcess] Task core.tasks.every_10_sec[13469f46-383a-4f58-bf60-86793d3ca7cb] succeeded in 0.000717100003384985s: 81
[2020-11-19 12:16:30,256: INFO/MainProcess] Received task: core.tasks.every_10_sec[410eab99-90c2-42d0-902d-e09f7f74f3cd]  
[2020-11-19 12:16:30,257: INFO/MainProcess] core.tasks.every_10_sec[410eab99-90c2-42d0-902d-e09f7f74f3cd]: Run every 10sec methods
[2020-11-19 12:16:30,257: INFO/MainProcess] core.tasks.every_10_sec[410eab99-90c2-42d0-902d-e09f7f74f3cd]: result: 175
[2020-11-19 12:16:30,258: INFO/MainProcess] Task core.tasks.every_10_sec[410eab99-90c2-42d0-902d-e09f7f74f3cd] succeeded in 0.000911899987841025s: 175
[2020-11-19 12:16:30,259: INFO/MainProcess] Received task: core.tasks.every_10_sec[50a7739a-591d-4a67-83a4-027ca51fddc4]  
[2020-11-19 12:16:30,260: INFO/MainProcess] core.tasks.every_10_sec[50a7739a-591d-4a67-83a4-027ca51fddc4]: Run every 10sec methods
[2020-11-19 12:16:30,260: INFO/MainProcess] core.tasks.every_10_sec[50a7739a-591d-4a67-83a4-027ca51fddc4]: result: 115
[2020-11-19 12:16:30,261: INFO/MainProcess] Task core.tasks.every_10_sec[50a7739a-591d-4a67-83a4-027ca51fddc4] succeeded in 0.0007678999972995371s: 115
[2020-11-19 12:16:30,262: INFO/MainProcess] Received task: core.tasks.every_30_sec[64025a7f-217e-4630-b900-4e5cd88801b1]  
[2020-11-19 12:16:30,263: INFO/MainProcess] core.tasks.every_30_sec[64025a7f-217e-4630-b900-4e5cd88801b1]: Run every 30sec methods
[2020-11-19 12:16:30,263: INFO/MainProcess] core.tasks.every_30_sec[64025a7f-217e-4630-b900-4e5cd88801b1]: result: 404
[2020-11-19 12:16:30,264: INFO/MainProcess] Task core.tasks.every_30_sec[64025a7f-217e-4630-b900-4e5cd88801b1] succeeded in 0.000745400000596419s: 404
[2020-11-19 12:16:30,265: INFO/MainProcess] Received task: core.tasks.every_60_sec[39eace9e-81ce-4246-a6a2-36e774ee93f7]  
[2020-11-19 12:16:30,266: INFO/MainProcess] core.tasks.every_60_sec[39eace9e-81ce-4246-a6a2-36e774ee93f7]: Run every 60sec methods
[2020-11-19 12:16:30,266: INFO/MainProcess] core.tasks.every_60_sec[39eace9e-81ce-4246-a6a2-36e774ee93f7]: result: 857
[2020-11-19 12:16:30,266: INFO/MainProcess] Task core.tasks.every_60_sec[39eace9e-81ce-4246-a6a2-36e774ee93f7] succeeded in 0.0007695999956922606s: 857
[2020-11-19 12:16:30,268: INFO/MainProcess] Received task: core.tasks.every_10_sec[9910c411-7cd9-45d5-b02f-1ea875f1cdeb]  
[2020-11-19 12:16:30,269: INFO/MainProcess] core.tasks.every_10_sec[9910c411-7cd9-45d5-b02f-1ea875f1cdeb]: Run every 10sec methods
[2020-11-19 12:16:30,269: INFO/MainProcess] core.tasks.every_10_sec[9910c411-7cd9-45d5-b02f-1ea875f1cdeb]: result: 71
[2020-11-19 12:16:30,269: INFO/MainProcess] Task core.tasks.every_10_sec[9910c411-7cd9-45d5-b02f-1ea875f1cdeb] succeeded in 0.0007623999990755692s: 71
[2020-11-19 12:16:30,271: INFO/MainProcess] Received task: core.tasks.every_10_sec[50c9afe6-f322-4a01-89f0-b5a22bbfbe0c]  
[2020-11-19 12:16:30,272: INFO/MainProcess] core.tasks.every_10_sec[50c9afe6-f322-4a01-89f0-b5a22bbfbe0c]: Run every 10sec methods
[2020-11-19 12:16:30,272: INFO/MainProcess] core.tasks.every_10_sec[50c9afe6-f322-4a01-89f0-b5a22bbfbe0c]: result: 124
[2020-11-19 12:16:30,272: INFO/MainProcess] Task core.tasks.every_10_sec[50c9afe6-f322-4a01-89f0-b5a22bbfbe0c] succeeded in 0.0008322999929077923s: 124
[2020-11-19 12:16:30,275: INFO/MainProcess] Received task: core.tasks.every_10_sec[d56a7245-341b-4f2c-9240-54d21725e7fd]  
[2020-11-19 12:16:30,275: INFO/MainProcess] core.tasks.every_10_sec[d56a7245-341b-4f2c-9240-54d21725e7fd]: Run every 10sec methods
[2020-11-19 12:16:30,276: INFO/MainProcess] core.tasks.every_10_sec[d56a7245-341b-4f2c-9240-54d21725e7fd]: result: 195
[2020-11-19 12:16:30,276: INFO/MainProcess] Task core.tasks.every_10_sec[d56a7245-341b-4f2c-9240-54d21725e7fd] succeeded in 0.0008773000008659437s: 195
[2020-11-19 12:16:30,278: INFO/MainProcess] Received task: core.tasks.every_30_sec[8695ed00-a1b3-42bb-b8ba-f5741c0b331b]  
[2020-11-19 12:16:30,279: INFO/MainProcess] core.tasks.every_30_sec[8695ed00-a1b3-42bb-b8ba-f5741c0b331b]: Run every 30sec methods
[2020-11-19 12:16:30,279: INFO/MainProcess] core.tasks.every_30_sec[8695ed00-a1b3-42bb-b8ba-f5741c0b331b]: result: 393
[2020-11-19 12:16:30,279: INFO/MainProcess] Task core.tasks.every_30_sec[8695ed00-a1b3-42bb-b8ba-f5741c0b331b] succeeded in 0.000785700001870282s: 393
[2020-11-19 12:16:30,281: INFO/MainProcess] Received task: core.tasks.every_10_sec[a9314f1a-8a89-4645-91e7-1c85520aae2b]  
[2020-11-19 12:16:30,281: INFO/MainProcess] core.tasks.every_10_sec[a9314f1a-8a89-4645-91e7-1c85520aae2b]: Run every 10sec methods
[2020-11-19 12:16:30,282: INFO/MainProcess] core.tasks.every_10_sec[a9314f1a-8a89-4645-91e7-1c85520aae2b]: result: 103
[2020-11-19 12:16:30,282: INFO/MainProcess] Task core.tasks.every_10_sec[a9314f1a-8a89-4645-91e7-1c85520aae2b] succeeded in 0.0007836000004317611s: 103
[2020-11-19 12:16:30,284: INFO/MainProcess] Received task: core.tasks.every_10_sec[e6ddd094-ed05-4ba1-887a-5bc7788cc086]  
[2020-11-19 12:16:30,284: INFO/MainProcess] core.tasks.every_10_sec[e6ddd094-ed05-4ba1-887a-5bc7788cc086]: Run every 10sec methods
[2020-11-19 12:16:30,285: INFO/MainProcess] core.tasks.every_10_sec[e6ddd094-ed05-4ba1-887a-5bc7788cc086]: result: 134
[2020-11-19 12:16:30,285: INFO/MainProcess] Task core.tasks.every_10_sec[e6ddd094-ed05-4ba1-887a-5bc7788cc086] succeeded in 0.0007385000062640756s: 134
[2020-11-19 12:16:30,287: INFO/MainProcess] Received task: core.tasks.every_10_sec[ec7ae3e6-4101-4133-b117-15f734d4e678]  
[2020-11-19 12:16:30,287: INFO/MainProcess] core.tasks.every_10_sec[ec7ae3e6-4101-4133-b117-15f734d4e678]: Run every 10sec methods
[2020-11-19 12:16:30,288: INFO/MainProcess] core.tasks.every_10_sec[ec7ae3e6-4101-4133-b117-15f734d4e678]: result: 78
[2020-11-19 12:16:30,288: INFO/MainProcess] Task core.tasks.every_10_sec[ec7ae3e6-4101-4133-b117-15f734d4e678] succeeded in 0.00077860000601504s: 78
[2020-11-19 12:16:30,290: INFO/MainProcess] Received task: core.tasks.every_30_sec[fc35721a-2f9b-4a10-8c1d-7278d31a46be]  
[2020-11-19 12:16:30,290: INFO/MainProcess] core.tasks.every_30_sec[fc35721a-2f9b-4a10-8c1d-7278d31a46be]: Run every 30sec methods
[2020-11-19 12:16:30,291: INFO/MainProcess] core.tasks.every_30_sec[fc35721a-2f9b-4a10-8c1d-7278d31a46be]: result: 449
[2020-11-19 12:16:30,291: INFO/MainProcess] Task core.tasks.every_30_sec[fc35721a-2f9b-4a10-8c1d-7278d31a46be] succeeded in 0.0008055000071180984s: 449
[2020-11-19 12:16:30,293: INFO/MainProcess] Received task: core.tasks.every_60_sec[e0bae1bc-e40b-4e42-8464-77ee3a917ac1]  
[2020-11-19 12:16:30,293: INFO/MainProcess] core.tasks.every_60_sec[e0bae1bc-e40b-4e42-8464-77ee3a917ac1]: Run every 60sec methods
[2020-11-19 12:16:30,293: INFO/MainProcess] core.tasks.every_60_sec[e0bae1bc-e40b-4e42-8464-77ee3a917ac1]: result: 818
[2020-11-19 12:16:30,294: INFO/MainProcess] Task core.tasks.every_60_sec[e0bae1bc-e40b-4e42-8464-77ee3a917ac1] succeeded in 0.0007506999972974882s: 818
[2020-11-19 12:16:30,295: INFO/MainProcess] Received task: core.tasks.every_10_sec[ded3d94e-3b6f-46af-a5c1-b38b02aa1fce]  
[2020-11-19 12:16:30,296: INFO/MainProcess] core.tasks.every_10_sec[ded3d94e-3b6f-46af-a5c1-b38b02aa1fce]: Run every 10sec methods
[2020-11-19 12:16:30,296: INFO/MainProcess] core.tasks.every_10_sec[ded3d94e-3b6f-46af-a5c1-b38b02aa1fce]: result: 119
[2020-11-19 12:16:30,297: INFO/MainProcess] Task core.tasks.every_10_sec[ded3d94e-3b6f-46af-a5c1-b38b02aa1fce] succeeded in 0.0007341999880736694s: 119
[2020-11-19 12:16:30,298: INFO/MainProcess] Received task: core.tasks.every_10_sec[fdacc4e3-e5e2-42a5-bd72-00482fbb823f]  
[2020-11-19 12:16:30,299: INFO/MainProcess] core.tasks.every_10_sec[fdacc4e3-e5e2-42a5-bd72-00482fbb823f]: Run every 10sec methods
[2020-11-19 12:16:30,299: INFO/MainProcess] core.tasks.every_10_sec[fdacc4e3-e5e2-42a5-bd72-00482fbb823f]: result: 103
[2020-11-19 12:16:30,299: INFO/MainProcess] Task core.tasks.every_10_sec[fdacc4e3-e5e2-42a5-bd72-00482fbb823f] succeeded in 0.0007412999984808266s: 103
[2020-11-19 12:16:30,301: INFO/MainProcess] Received task: core.tasks.every_10_sec[a4cd9f82-facf-4dda-9ffd-219017bf731b]  
[2020-11-19 12:16:30,302: INFO/MainProcess] core.tasks.every_10_sec[a4cd9f82-facf-4dda-9ffd-219017bf731b]: Run every 10sec methods
[2020-11-19 12:16:30,302: INFO/MainProcess] core.tasks.every_10_sec[a4cd9f82-facf-4dda-9ffd-219017bf731b]: result: 39
[2020-11-19 12:16:30,303: INFO/MainProcess] Task core.tasks.every_10_sec[a4cd9f82-facf-4dda-9ffd-219017bf731b] succeeded in 0.0008996999968076125s: 39
[2020-11-19 12:16:30,305: INFO/MainProcess] Received task: core.tasks.every_30_sec[3a680349-c95c-41c1-ace2-5af32cc9d05b]  
[2020-11-19 12:16:30,305: INFO/MainProcess] core.tasks.every_30_sec[3a680349-c95c-41c1-ace2-5af32cc9d05b]: Run every 30sec methods
[2020-11-19 12:16:30,305: INFO/MainProcess] core.tasks.every_30_sec[3a680349-c95c-41c1-ace2-5af32cc9d05b]: result: 412
[2020-11-19 12:16:30,306: INFO/MainProcess] Task core.tasks.every_30_sec[3a680349-c95c-41c1-ace2-5af32cc9d05b] succeeded in 0.0008350999996764585s: 412
[2020-11-19 12:16:30,308: INFO/MainProcess] Received task: core.tasks.every_10_sec[0055831e-81be-4940-9ac5-68f7ae0e72db]  
[2020-11-19 12:16:30,309: INFO/MainProcess] core.tasks.every_10_sec[0055831e-81be-4940-9ac5-68f7ae0e72db]: Run every 10sec methods
[2020-11-19 12:16:30,309: INFO/MainProcess] core.tasks.every_10_sec[0055831e-81be-4940-9ac5-68f7ae0e72db]: result: 25
[2020-11-19 12:16:30,310: INFO/MainProcess] Task core.tasks.every_10_sec[0055831e-81be-4940-9ac5-68f7ae0e72db] succeeded in 0.0008452000038232654s: 25
[2020-11-19 12:16:30,312: INFO/MainProcess] Received task: core.tasks.every_10_sec[313f229e-d685-4e46-a624-f7d66798e6c0]  
[2020-11-19 12:16:30,312: INFO/MainProcess] core.tasks.every_10_sec[313f229e-d685-4e46-a624-f7d66798e6c0]: Run every 10sec methods
[2020-11-19 12:16:30,312: INFO/MainProcess] core.tasks.every_10_sec[313f229e-d685-4e46-a624-f7d66798e6c0]: result: 156
[2020-11-19 12:16:30,313: INFO/MainProcess] Task core.tasks.every_10_sec[313f229e-d685-4e46-a624-f7d66798e6c0] succeeded in 0.0007622999983141199s: 156
[2020-11-19 12:16:30,315: INFO/MainProcess] Received task: core.tasks.every_10_sec[0d82d64f-372f-4b19-b727-a28b9aa87ed8]  
[2020-11-19 12:16:30,315: INFO/MainProcess] core.tasks.every_10_sec[0d82d64f-372f-4b19-b727-a28b9aa87ed8]: Run every 10sec methods
[2020-11-19 12:16:30,315: INFO/MainProcess] core.tasks.every_10_sec[0d82d64f-372f-4b19-b727-a28b9aa87ed8]: result: 116
[2020-11-19 12:16:30,316: INFO/MainProcess] Task core.tasks.every_10_sec[0d82d64f-372f-4b19-b727-a28b9aa87ed8] succeeded in 0.0007391999970423058s: 116
[2020-11-19 12:16:30,317: INFO/MainProcess] Received task: core.tasks.every_30_sec[16557749-2c9b-4447-8361-33ef3357069c]  
[2020-11-19 12:16:30,318: INFO/MainProcess] core.tasks.every_30_sec[16557749-2c9b-4447-8361-33ef3357069c]: Run every 30sec methods
[2020-11-19 12:16:30,318: INFO/MainProcess] core.tasks.every_30_sec[16557749-2c9b-4447-8361-33ef3357069c]: result: 397
[2020-11-19 12:16:30,319: INFO/MainProcess] Task core.tasks.every_30_sec[16557749-2c9b-4447-8361-33ef3357069c] succeeded in 0.0007190999895101413s: 397
[2020-11-19 12:16:30,320: INFO/MainProcess] Received task: core.tasks.every_60_sec[dc8d17cb-f238-4a22-aa5b-ce1957f69f02]  
[2020-11-19 12:16:30,321: INFO/MainProcess] core.tasks.every_60_sec[dc8d17cb-f238-4a22-aa5b-ce1957f69f02]: Run every 60sec methods
[2020-11-19 12:16:30,321: INFO/MainProcess] core.tasks.every_60_sec[dc8d17cb-f238-4a22-aa5b-ce1957f69f02]: result: 723
[2020-11-19 12:16:30,321: INFO/MainProcess] Task core.tasks.every_60_sec[dc8d17cb-f238-4a22-aa5b-ce1957f69f02] succeeded in 0.0007392999978037551s: 723
[2020-11-19 12:16:30,323: INFO/MainProcess] Received task: core.tasks.every_10_sec[c9bb7008-88e3-4067-b382-c28cced67056]  
[2020-11-19 12:16:30,324: INFO/MainProcess] core.tasks.every_10_sec[c9bb7008-88e3-4067-b382-c28cced67056]: Run every 10sec methods
[2020-11-19 12:16:30,324: INFO/MainProcess] core.tasks.every_10_sec[c9bb7008-88e3-4067-b382-c28cced67056]: result: 76
[2020-11-19 12:16:30,324: INFO/MainProcess] Task core.tasks.every_10_sec[c9bb7008-88e3-4067-b382-c28cced67056] succeeded in 0.0007592000038130209s: 76
[2020-11-19 12:16:30,326: INFO/MainProcess] Received task: core.tasks.every_10_sec[fdd387eb-0040-456b-9166-84c070fb3c53]  
[2020-11-19 12:16:30,327: INFO/MainProcess] core.tasks.every_10_sec[fdd387eb-0040-456b-9166-84c070fb3c53]: Run every 10sec methods
[2020-11-19 12:16:30,327: INFO/MainProcess] core.tasks.every_10_sec[fdd387eb-0040-456b-9166-84c070fb3c53]: result: 63
[2020-11-19 12:16:30,328: INFO/MainProcess] Task core.tasks.every_10_sec[fdd387eb-0040-456b-9166-84c070fb3c53] succeeded in 0.000753400003304705s: 63
[2020-11-19 12:16:30,329: INFO/MainProcess] Received task: core.tasks.every_10_sec[29068482-1cf3-45ea-91de-15851f4c2a4d]  
[2020-11-19 12:16:30,330: INFO/MainProcess] core.tasks.every_10_sec[29068482-1cf3-45ea-91de-15851f4c2a4d]: Run every 10sec methods
[2020-11-19 12:16:30,330: INFO/MainProcess] core.tasks.every_10_sec[29068482-1cf3-45ea-91de-15851f4c2a4d]: result: 54
[2020-11-19 12:16:30,331: INFO/MainProcess] Task core.tasks.every_10_sec[29068482-1cf3-45ea-91de-15851f4c2a4d] succeeded in 0.0007195000071078539s: 54
[2020-11-19 12:16:30,332: INFO/MainProcess] Received task: core.tasks.every_30_sec[47836cb9-5199-4e78-90be-3306bb4c95ad]  
[2020-11-19 12:16:30,333: INFO/MainProcess] core.tasks.every_30_sec[47836cb9-5199-4e78-90be-3306bb4c95ad]: Run every 30sec methods
[2020-11-19 12:16:30,333: INFO/MainProcess] core.tasks.every_30_sec[47836cb9-5199-4e78-90be-3306bb4c95ad]: result: 453
[2020-11-19 12:16:30,333: INFO/MainProcess] Task core.tasks.every_30_sec[47836cb9-5199-4e78-90be-3306bb4c95ad] succeeded in 0.0007990000012796372s: 453
[2020-11-19 12:16:30,335: INFO/MainProcess] Received task: core.tasks.every_10_sec[3ebec51c-cff6-4488-b84b-7c5e268ed2a0]  
[2020-11-19 12:16:30,336: INFO/MainProcess] core.tasks.every_10_sec[3ebec51c-cff6-4488-b84b-7c5e268ed2a0]: Run every 10sec methods
[2020-11-19 12:16:30,336: INFO/MainProcess] core.tasks.every_10_sec[3ebec51c-cff6-4488-b84b-7c5e268ed2a0]: result: 137
[2020-11-19 12:16:30,336: INFO/MainProcess] Task core.tasks.every_10_sec[3ebec51c-cff6-4488-b84b-7c5e268ed2a0] succeeded in 0.0007912000000942498s: 137
[2020-11-19 12:16:30,338: INFO/MainProcess] Received task: core.tasks.every_10_sec[d3037432-530f-4a06-8afc-89d21c1688b8]  
[2020-11-19 12:16:30,338: INFO/MainProcess] core.tasks.every_10_sec[d3037432-530f-4a06-8afc-89d21c1688b8]: Run every 10sec methods
[2020-11-19 12:16:30,339: INFO/MainProcess] core.tasks.every_10_sec[d3037432-530f-4a06-8afc-89d21c1688b8]: result: 65
[2020-11-19 12:16:30,339: INFO/MainProcess] Task core.tasks.every_10_sec[d3037432-530f-4a06-8afc-89d21c1688b8] succeeded in 0.0007222999993246049s: 65
[2020-11-19 12:16:30,341: INFO/MainProcess] Received task: core.tasks.every_10_sec[5034218e-52ae-4a1a-b03c-71c0fc72681e]  
[2020-11-19 12:16:30,342: INFO/MainProcess] core.tasks.every_10_sec[5034218e-52ae-4a1a-b03c-71c0fc72681e]: Run every 10sec methods
[2020-11-19 12:16:30,342: INFO/MainProcess] core.tasks.every_10_sec[5034218e-52ae-4a1a-b03c-71c0fc72681e]: result: 61
[2020-11-19 12:16:30,342: INFO/MainProcess] Task core.tasks.every_10_sec[5034218e-52ae-4a1a-b03c-71c0fc72681e] succeeded in 0.0008243999909609556s: 61
[2020-11-19 12:16:30,344: INFO/MainProcess] Received task: core.tasks.every_30_sec[31737ce8-42ba-4a4c-90c4-2f663d929b91]  
[2020-11-19 12:16:30,345: INFO/MainProcess] core.tasks.every_30_sec[31737ce8-42ba-4a4c-90c4-2f663d929b91]: Run every 30sec methods
[2020-11-19 12:16:30,345: INFO/MainProcess] core.tasks.every_30_sec[31737ce8-42ba-4a4c-90c4-2f663d929b91]: result: 363
[2020-11-19 12:16:30,346: INFO/MainProcess] Task core.tasks.every_30_sec[31737ce8-42ba-4a4c-90c4-2f663d929b91] succeeded in 0.000789400000940077s: 363
[2020-11-19 12:16:30,347: INFO/MainProcess] Received task: core.tasks.every_60_sec[711c719b-6f7e-4553-bd5b-744631707302]  
[2020-11-19 12:16:30,348: INFO/MainProcess] core.tasks.every_60_sec[711c719b-6f7e-4553-bd5b-744631707302]: Run every 60sec methods
[2020-11-19 12:16:30,348: INFO/MainProcess] core.tasks.every_60_sec[711c719b-6f7e-4553-bd5b-744631707302]: result: 768
[2020-11-19 12:16:30,348: INFO/MainProcess] Task core.tasks.every_60_sec[711c719b-6f7e-4553-bd5b-744631707302] succeeded in 0.0007553999894298613s: 768
[2020-11-19 12:16:30,350: INFO/MainProcess] Received task: core.tasks.every_10_sec[62e35921-2a2d-4cdf-8b04-8f5052869c73]  
[2020-11-19 12:16:30,351: INFO/MainProcess] core.tasks.every_10_sec[62e35921-2a2d-4cdf-8b04-8f5052869c73]: Run every 10sec methods
[2020-11-19 12:16:30,351: INFO/MainProcess] core.tasks.every_10_sec[62e35921-2a2d-4cdf-8b04-8f5052869c73]: result: 105
[2020-11-19 12:16:30,352: INFO/MainProcess] Task core.tasks.every_10_sec[62e35921-2a2d-4cdf-8b04-8f5052869c73] succeeded in 0.0008262000046670437s: 105
[2020-11-19 12:16:30,353: INFO/MainProcess] Received task: core.tasks.every_10_sec[06274be7-e856-4469-9a43-f2d1ad48e426]  
[2020-11-19 12:16:30,354: INFO/MainProcess] core.tasks.every_10_sec[06274be7-e856-4469-9a43-f2d1ad48e426]: Run every 10sec methods
[2020-11-19 12:16:30,354: INFO/MainProcess] core.tasks.every_10_sec[06274be7-e856-4469-9a43-f2d1ad48e426]: result: 86
[2020-11-19 12:16:30,354: INFO/MainProcess] Task core.tasks.every_10_sec[06274be7-e856-4469-9a43-f2d1ad48e426] succeeded in 0.0007361000025412068s: 86
[2020-11-19 12:16:30,356: INFO/MainProcess] Received task: core.tasks.every_10_sec[b473d547-2d1a-484f-8a57-2034556a5ba5]  
[2020-11-19 12:16:30,357: INFO/MainProcess] core.tasks.every_10_sec[b473d547-2d1a-484f-8a57-2034556a5ba5]: Run every 10sec methods
[2020-11-19 12:16:30,357: INFO/MainProcess] core.tasks.every_10_sec[b473d547-2d1a-484f-8a57-2034556a5ba5]: result: 82
[2020-11-19 12:16:30,358: INFO/MainProcess] Task core.tasks.every_10_sec[b473d547-2d1a-484f-8a57-2034556a5ba5] succeeded in 0.0009641999931773171s: 82
[2020-11-19 12:16:30,360: INFO/MainProcess] Received task: core.tasks.every_30_sec[cc13dd24-38ae-4ed5-9159-2d9b07c2d6d2]  
[2020-11-19 12:16:30,360: INFO/MainProcess] core.tasks.every_30_sec[cc13dd24-38ae-4ed5-9159-2d9b07c2d6d2]: Run every 30sec methods
[2020-11-19 12:16:30,360: INFO/MainProcess] core.tasks.every_30_sec[cc13dd24-38ae-4ed5-9159-2d9b07c2d6d2]: result: 380
[2020-11-19 12:16:30,361: INFO/MainProcess] Task core.tasks.every_30_sec[cc13dd24-38ae-4ed5-9159-2d9b07c2d6d2] succeeded in 0.0007691999926464632s: 380
[2020-11-19 12:16:30,362: INFO/MainProcess] Received task: core.tasks.every_10_sec[73e9bed2-9ada-415e-a714-33e676f1f5e5]  
[2020-11-19 12:16:30,363: INFO/MainProcess] core.tasks.every_10_sec[73e9bed2-9ada-415e-a714-33e676f1f5e5]: Run every 10sec methods
[2020-11-19 12:16:30,363: INFO/MainProcess] core.tasks.every_10_sec[73e9bed2-9ada-415e-a714-33e676f1f5e5]: result: 102
[2020-11-19 12:16:30,364: INFO/MainProcess] Task core.tasks.every_10_sec[73e9bed2-9ada-415e-a714-33e676f1f5e5] succeeded in 0.0007432999991578981s: 102
[2020-11-19 12:16:30,365: INFO/MainProcess] Received task: core.tasks.every_10_sec[1a6f9e74-5055-4e02-9dad-616475fbe8a0]  
[2020-11-19 12:16:30,366: INFO/MainProcess] core.tasks.every_10_sec[1a6f9e74-5055-4e02-9dad-616475fbe8a0]: Run every 10sec methods
[2020-11-19 12:16:30,366: INFO/MainProcess] core.tasks.every_10_sec[1a6f9e74-5055-4e02-9dad-616475fbe8a0]: result: 78
[2020-11-19 12:16:30,367: INFO/MainProcess] Task core.tasks.every_10_sec[1a6f9e74-5055-4e02-9dad-616475fbe8a0] succeeded in 0.0007668000034755096s: 78
[2020-11-19 12:16:30,368: INFO/MainProcess] Received task: core.tasks.every_10_sec[83df7926-28fe-4469-a31b-d7c51af3ff9f]  
[2020-11-19 12:16:30,369: INFO/MainProcess] core.tasks.every_10_sec[83df7926-28fe-4469-a31b-d7c51af3ff9f]: Run every 10sec methods
[2020-11-19 12:16:30,369: INFO/MainProcess] core.tasks.every_10_sec[83df7926-28fe-4469-a31b-d7c51af3ff9f]: result: 139
[2020-11-19 12:16:30,369: INFO/MainProcess] Task core.tasks.every_10_sec[83df7926-28fe-4469-a31b-d7c51af3ff9f] succeeded in 0.0007652999920537695s: 139
[2020-11-19 12:16:30,371: INFO/MainProcess] Received task: core.tasks.every_30_sec[eaeb6473-878c-4b95-aeee-5ddcfd01ee8a]  
[2020-11-19 12:16:30,372: INFO/MainProcess] core.tasks.every_30_sec[eaeb6473-878c-4b95-aeee-5ddcfd01ee8a]: Run every 30sec methods
[2020-11-19 12:16:30,372: INFO/MainProcess] core.tasks.every_30_sec[eaeb6473-878c-4b95-aeee-5ddcfd01ee8a]: result: 389
[2020-11-19 12:16:30,372: INFO/MainProcess] Task core.tasks.every_30_sec[eaeb6473-878c-4b95-aeee-5ddcfd01ee8a] succeeded in 0.0007348999934038147s: 389
[2020-11-19 12:16:30,374: INFO/MainProcess] Received task: core.tasks.every_60_sec[0b9fe424-7714-410e-99e2-01c24dc2de19]  
[2020-11-19 12:16:30,375: INFO/MainProcess] core.tasks.every_60_sec[0b9fe424-7714-410e-99e2-01c24dc2de19]: Run every 60sec methods
[2020-11-19 12:16:30,375: INFO/MainProcess] core.tasks.every_60_sec[0b9fe424-7714-410e-99e2-01c24dc2de19]: result: 788
[2020-11-19 12:16:30,376: INFO/MainProcess] Task core.tasks.every_60_sec[0b9fe424-7714-410e-99e2-01c24dc2de19] succeeded in 0.0007920999923953786s: 788
[2020-11-19 12:16:30,378: INFO/MainProcess] Received task: core.tasks.every_10_sec[b522e9bd-a1e2-469b-a7ff-0df04c86006d]  
[2020-11-19 12:16:30,378: INFO/MainProcess] core.tasks.every_10_sec[b522e9bd-a1e2-469b-a7ff-0df04c86006d]: Run every 10sec methods
[2020-11-19 12:16:30,378: INFO/MainProcess] core.tasks.every_10_sec[b522e9bd-a1e2-469b-a7ff-0df04c86006d]: result: 104
[2020-11-19 12:16:30,379: INFO/MainProcess] Task core.tasks.every_10_sec[b522e9bd-a1e2-469b-a7ff-0df04c86006d] succeeded in 0.0007411999977193773s: 104
[2020-11-19 12:16:30,380: INFO/MainProcess] Received task: core.tasks.every_10_sec[d894997a-a53a-400f-b7d2-81bbf9882ceb]  
[2020-11-19 12:16:30,381: INFO/MainProcess] core.tasks.every_10_sec[d894997a-a53a-400f-b7d2-81bbf9882ceb]: Run every 10sec methods
[2020-11-19 12:16:30,381: INFO/MainProcess] core.tasks.every_10_sec[d894997a-a53a-400f-b7d2-81bbf9882ceb]: result: 88
[2020-11-19 12:16:30,381: INFO/MainProcess] Task core.tasks.every_10_sec[d894997a-a53a-400f-b7d2-81bbf9882ceb] succeeded in 0.0007409999961964786s: 88
[2020-11-19 12:20:58,769: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 12:21:00,777: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 12:21:04,787: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 12:21:10,799: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 12:21:18,813: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 12:21:28,829: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 12:21:40,848: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 12:21:54,868: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 12:22:10,893: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 12:22:28,917: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 12:22:48,945: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 12:23:10,973: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 12:23:35,004: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 12:24:01,036: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 12:24:29,071: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 12:24:59,110: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:25:02,709: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 12:25:04,717: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 12:25:08,726: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 12:25:14,738: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 12:25:22,753: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 12:25:31,149: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:25:32,769: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 12:25:44,787: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 12:25:58,808: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 12:26:03,189: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:26:14,830: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 12:26:32,855: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 12:26:35,228: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:26:52,882: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 12:27:07,268: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:27:14,911: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 12:27:38,942: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 12:27:39,307: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:28:04,975: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 12:28:11,346: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:28:33,010: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 12:28:43,386: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:29:03,047: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:29:15,425: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:29:35,086: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:29:47,464: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:30:07,126: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:30:19,505: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:30:39,166: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:30:51,544: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:31:11,206: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:31:23,584: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:31:43,245: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:31:55,622: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:32:15,284: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:32:27,662: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:32:47,323: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:32:59,701: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:33:19,361: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:33:31,741: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:34:35,056: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 12:34:37,064: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 12:34:41,074: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 12:34:47,085: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 12:34:55,099: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 12:35:05,115: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 12:35:17,134: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 12:35:31,154: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 12:35:54,858: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 12:35:56,865: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 12:36:00,875: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 12:36:06,887: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 12:36:14,901: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 12:36:24,918: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 12:36:41,889: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 12:36:43,897: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 12:36:47,907: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 12:36:53,919: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 12:37:01,933: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 12:37:11,949: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 12:37:23,967: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 12:37:37,987: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 12:37:54,010: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 12:38:12,035: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 12:38:32,062: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 12:38:54,091: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 12:39:18,122: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 12:39:44,155: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 12:40:12,190: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 12:40:42,227: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:41:14,265: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:41:46,303: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:42:18,341: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:42:50,380: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:43:22,420: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:43:54,458: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:44:26,497: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:44:58,536: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:45:30,575: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:46:02,614: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:46:34,653: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:47:06,692: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:47:38,732: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:48:10,771: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:48:42,810: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:49:14,849: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:49:46,888: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:50:18,928: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:50:50,965: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 12:51:23,003: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:50:53,219: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 13:50:55,226: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 13:50:59,236: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 13:51:05,248: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 13:51:13,262: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 13:51:23,279: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 13:51:35,297: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 13:51:49,318: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 13:52:05,341: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 13:52:23,365: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 13:52:43,391: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 13:53:05,420: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 13:53:29,451: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 13:53:55,484: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 13:54:23,519: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 13:54:53,556: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:55:25,596: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:55:57,636: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:56:29,675: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:57:01,713: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:57:33,753: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:58:05,794: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:58:37,833: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:59:09,873: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 13:59:41,911: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:00:13,950: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:00:45,990: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:01:18,030: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:01:50,069: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:02:22,108: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:02:54,147: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:03:26,187: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:03:58,227: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:04:30,267: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:05:02,306: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:05:34,343: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:06:06,381: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:06:38,420: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:07:10,457: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:07:42,495: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:08:14,535: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:08:46,574: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:09:18,614: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:09:50,653: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:10:22,692: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:10:54,731: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:11:26,771: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:11:58,811: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:12:30,850: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:13:02,889: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:13:34,929: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:14:06,977: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:14:39,016: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:15:11,055: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:15:43,094: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:16:15,133: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:16:47,170: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:17:19,208: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:17:51,248: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:18:23,288: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:18:55,327: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:19:27,365: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:19:59,405: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:20:31,444: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:21:03,483: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:21:35,522: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:22:07,561: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:22:39,600: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:23:11,640: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:23:43,679: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:24:15,719: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:24:47,757: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:25:19,797: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:25:51,836: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:26:23,875: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:27:30,323: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:27:32,331: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 14:27:36,341: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 14:27:42,353: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 14:27:50,367: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 14:28:00,383: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 14:28:12,401: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 14:28:26,421: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 14:28:42,444: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 14:29:00,468: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 14:29:37,321: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:29:39,328: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 14:29:43,338: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 14:29:49,350: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 14:29:57,364: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 14:30:07,381: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 14:30:19,398: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 14:30:33,418: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 14:30:49,441: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 14:31:07,464: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 14:31:27,491: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 14:31:49,520: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 14:32:13,551: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 14:32:39,584: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 14:33:07,616: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 14:33:37,653: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:34:09,692: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:34:41,732: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:35:13,769: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:35:45,808: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:36:17,847: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:36:49,886: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:37:29,303: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:37:31,311: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 14:37:35,321: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 14:37:41,332: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 14:37:49,345: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 14:37:59,361: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 14:38:11,380: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 14:38:25,400: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 14:38:41,422: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 14:40:23,897: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:40:25,904: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 14:40:29,914: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 14:40:35,926: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 14:40:43,940: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 14:40:53,957: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 14:41:05,976: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 14:41:19,996: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 14:41:36,018: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 14:41:54,043: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 14:42:14,070: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 14:42:36,099: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 14:43:00,130: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2020-11-19 14:43:26,164: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2020-11-19 14:43:54,199: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2020-11-19 14:44:24,235: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:44:56,275: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:45:28,314: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:46:00,353: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:46:32,392: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:47:04,432: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2020-11-19 14:47:44,499: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:47:46,507: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 14:47:50,517: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 14:48:08,627: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:48:25,134: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 14:48:27,141: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 14:48:31,151: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 14:48:37,162: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 14:48:45,176: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 14:48:55,192: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 14:49:07,211: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 14:49:21,232: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 14:49:37,254: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 14:49:55,279: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 14:50:15,305: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 16:32:54,823: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 16:32:56,830: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 16:33:00,840: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 16:33:06,852: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 16:33:14,866: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 16:33:24,882: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 16:33:36,900: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 16:33:50,921: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 16:34:06,944: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 16:34:59,314: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 16:35:01,322: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 16:35:05,331: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 16:35:11,343: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 16:35:19,357: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 16:35:29,373: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 16:35:41,392: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 16:35:55,413: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 16:36:11,435: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2020-11-19 16:36:29,460: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2020-11-19 16:36:49,487: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2020-11-19 16:37:11,516: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2020-11-19 16:38:25,935: INFO/MainProcess] Connected to redis://broker:6379//
[2020-11-19 16:38:25,946: INFO/MainProcess] celery@myhost ready.
[2020-11-19 16:38:31,595: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:38:31,634: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_30_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_30_sec'
[2020-11-19 16:38:31,641: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_60_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_60_sec'
[2020-11-19 16:38:41,581: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:38:51,583: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:39:01,584: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:39:01,636: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_30_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_30_sec'
[2020-11-19 16:39:11,586: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:39:21,588: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:39:31,589: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:39:31,639: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_30_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_30_sec'
[2020-11-19 16:39:31,647: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_60_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_60_sec'
[2020-11-19 16:39:41,591: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:39:51,593: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:40:01,596: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:40:01,645: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_30_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_30_sec'
[2020-11-19 16:40:11,597: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:40:31,106: INFO/MainProcess] Connected to redis://broker:6379//
[2020-11-19 16:40:31,117: INFO/MainProcess] celery@myhost ready.
[2020-11-19 16:40:36,690: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:40:36,737: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_30_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_30_sec'
[2020-11-19 16:40:36,744: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_60_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_60_sec'
[2020-11-19 16:40:46,677: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:40:56,679: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:41:06,680: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_10_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_10_sec'
[2020-11-19 16:41:06,738: ERROR/MainProcess] Received unregistered task of type 'core.tasks.every_30_sec'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'core.tasks.every_30_sec'
[2020-11-19 16:42:11,793: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 16:42:13,800: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 16:42:17,810: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 16:42:23,822: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 16:42:31,836: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 16:42:41,853: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 16:42:53,871: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 16:43:07,891: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2020-11-19 16:43:29,987: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-11-19 16:43:31,996: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2020-11-19 16:43:36,006: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2020-11-19 16:43:42,017: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2020-11-19 16:43:50,031: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2020-11-19 16:44:00,048: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2020-11-19 16:44:12,068: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2020-11-19 16:44:26,089: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

